- docker/README.md
I decided against tucking a note somewhere else on the page explaining that you _should_ run this command by hand separately _iff_ you are hacking the repo without having run `composer install` (on the grounds that the page already has enough stuff on it). If you disagree, I'll add the note.
> Remove redundant hook instructions (fixes #92)

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/modules/cgov_home_landing/config/install/core.entity_form_display.node.cgov_home_landing.default.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/modules/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.default.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/modules/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_date_display_mode.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/modules/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_date_posted.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/modules/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_date_reviewed.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/modules/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_date_updated.yml
I'm not certain why content_moderation was there in `core.entity_form_display.node.cgov_home_landing.default.yml` , but it's being removed by the export process, so I left the removal there.
> Fixes #130 - Add common dates to Home_Landing

- docker/web/Dockerfile
Changes the `web` container's Dockerfile so login to the container defaults to `/var/www`.
> Issue #233 - Default web container to /var/www

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/PageOptions.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/PageOptionsManager.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/PageOptionsManagerInterface.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Unit/Plugin/Block/PageOptionsTest.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Unit/Plugin/Services/PageOptionsManagerTest.php
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block/page_options/block--page-options.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/node--cgov-article--full.html.twig
The following represents a first revision implementation of the custom Block Plugin and custom Service for Page Options. The service determines the current node type and returns an array of configuration associative arrays for the defined corresponding page options. The block plugin overrides the method blockAccess to allow for conditional rendering of the entire block without depending on a conditional in the twig template itself. The associated twig template in the cgov_common theme conditionally renders each page option type if a config object for it has been passed (future iterations will flesh the simple boolean out into a more complex array allowing for dynamic rendering of the constituent parts in the twig array (and subsequently, dynamic ordering)).
> Feature/141  page options block plugin

- composer.json
- composer.lock
- docroot/profiles/custom/cgov_site/cgov_site.info.yml
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/node--cgov-article--full.html.twig
The twig tweak library gives us a lot more flexibility for easily subverting the normal inheritance scheme of twig templates. This installs the module and uses it to insert the page options block into the node article template.
> Ticket/269  add twig tweak module

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/WorkflowTest.php
I have included the test for this new method by modifying `WorkflowTest.php` to invoke it instead of loading the workflow through the entity type manager directly.
It seems to me that as time goes on and the `CgovCoreTools` class is expanded to support more and more functionality that the argument list for the constructor is going to get pretty unwieldy. Not only is this ungainly and a bit hard to read in the code, but it's somewhat inefficient as well. As I understand it, one of the selling points for dependency injection is that the services needed for a component are only loaded when they are needed. However, that advantage starts to unravel when you build an omnibus service which in turn might need one or two of a bunch of other services, depending on which method of the new service …
> Add helper function to attach content types to workflow (closes #127)

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_search_engine_restrictions.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/FieldStorage/CGovFieldStorageTest.php
This matches the requirements of https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#search-engine-restrictions but the requirements are unusual.   I would expect this field to be a Boolean given the available options.   I heard it had additional options in the current implementation, and perhaps it will again (perhaps `Include in Site Search` and `Include in Internet Search` or something (though that may be better implemented as as `Site Search` boolean and an `Internet Search` boolean), so I have implemented it as listed.
If it is to be a boolean, the field name and labels should be changed accordingly so the display is not confusing (`[X] Search Engine Restrictions` would imply that there `are` restrictions, not that it should be included in the search).
> Fixes #200 Add Search Engine Restrictions field

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/workflows.workflow.editorial_workflow.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/WorkflowTest.php
This is my workaround for https://www.drupal.org/project/drupal/issues/3021222. I gave them the fix (though not as a patch with a new test). We'll see whether they get it into 8.7.0. If they do, the real fix should co-exist peacefully with our workaround until we are satisfied that we can drop it (this workaround, that is).
I noticed when I was testing the workaround that (after pulling down the latest mods from upstream) some, but not all of the moderation states are translated into Spanish. So "Published" becomes "Publicado" but we still have "Draft" and "Review." Seems like they have a ways to go sorting out the fine points of interactions between content translation and content moderation. 🤔
I also noticed that the order of the transitions determines the order of the available states …
> Fix available moderation states for new translation (fixes #371)

- composer.json
- composer.lock
- docker/web/Dockerfile
- patches/blt/issue-48-fix-behat-chrome-invocation.patch
I believe I have finally wrestled this one to the ground. I won't go into _all_ of the problems I ran into, but the highlights included very sketchy documentation (no information on how to generate the patch file or determine what the `--level` should be), next to no information provided when a patch fails, and the fact that `--dry-run` is useless when testing plugins (because there's no mechanism for `composer` to have the plugins say what they would do without doing it).
You have to run `composer cgov-clean` followed by `composer install` and then rebuild the containers. I did that, ran `blt setup` and then `blt tests:behat:run` and the `behat` tests ran and completed successfully.
> Install chrome and fix behat's invocation of it (fixes #48)

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/article/Article.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/README.md
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/index.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/index.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/types/customTweet.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/types/email.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/types/facebook.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/types/index.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/types/pinterest.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/types/print.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/types/resize.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/types/twitter.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/utilities/index.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/webpack.config.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/README.md
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/customEventHandler/README.md
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/customEventHandler/__tests__/index.test.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/customEventHandler/index.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/utilities/README.md
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/utilities/domManipulation.js
This marks the beginning of migrating the script assets we have. As a result, several extra changes were included. 
* The libraries directories and webpack aliases and the Common.js module code (heavily commented out to act as guide placeholders while we slowly flesh it out again). 
* Stub explanatory files were added to the directories to give a sense of where to place new or migrated assets.
* The page options partial was moved into its library scope and to maintain override hierarchy, the common.scss file import was moved to the top of common.js to allow libraries to override it as needed.
* page options relied on certain metadata elements to be extant that currently aren't. Extra checks/fallbacks were added to avoid errors. At the moment however, og:url nnot being there means things …
> Add page options script dependencies

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/core.entity_view_display.node.cgov_press_release.list_item_title_date_desc.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/core.entity_view_display.node.cgov_press_release.list_item_title_date_desc_image.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/core.entity_view_display.node.cgov_press_release.list_item_title_date_image.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/core.entity_view_display.node.cgov_press_release.list_item_title_desc.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/core.entity_view_display.node.cgov_press_release.list_item_title_desc_image.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/views.view.press_releases.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/press_release.content.yml
Add Press Release view blocks to system.  Also enables Config Translation module and removes a stray field label.
To create demo content:
- Enable Devel Generate
- Remove Press Releases from the Editorial workflow (can't publish via VBO while managed)
- Generate 50 English and 50 Spanish Content items
- Go to /admin/content, filter on Press Release, select all nodes and bulk Publish.
Fixes #299  
Helps #297 but doesn't close them, as the mini landing pages still need to be created.
> Add Press Release views

- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/field.field.node.cgov_article.field_site_section.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_site_section.yml
* Adds the target bundle for the Article and Home and Landing Site Section fields  (Press Releases already has it)
> Limit Site Section Field Settings to the Site Section Vocabulary.

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/NavItem.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/Breadcrumb.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/MainNav.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/SectionNav.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/CgovNavigationManager.php
An issue with Block level caching was causing issues on non-local environments. This PR handles:
- Adding a logger to Nav Manager Service (temporarily?)
- Removing caching on block plugins in a way that actually worked on the ODE
- Fix issue with spanish urls not getting /espanol path prepend
- Moving filtering of child terms from NavItem to plugin to reduce even more potential cache issues.
> Move NavItem filtering to plugin level to avoid cache issue

- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing.field_pretty_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/field.field.taxonomy_term.cgov_site_sections.field_pretty_url.yml
Add missing helper text to Mini Landing Page.
Update Pretty URL helper text for Site Section.
Closes #694.
(No seriously. It really does close it this time. (Probably.))
> Fix Pretty URL helper text

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/NavItem.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/SectionNav.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/CgovNavigationManager.php
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block/section_nav/block--cgov-section-nav.html.twig
For purposes of visual rendering, the section navigation needs to not only know when it's rendering the current site section for the request, but also whether the request was made from that site section's landing page. 
This fixes that by offering a service method and a navitem method to make that accessible to the section nav plugin. 
http://ncigovcdode25.prod.acquia-sites.com
> Ticket/904 Test for active site section improvement.

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/node--cgov-article--full.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/node--cgov-blog-post--full.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/event/node--cgov-event--full.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/image/field--field-image-article.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/press_release/node--cgov-press-release--full.html.twig
* We cannot override that template with the embed wrapper because it
breaks cards and lists.
> Removed the article image template

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/image/image_macros.twig
Fixed enlarge button.
There was an errant enlarge_uri[0] check - XDebug failed to handle this well.
> I hate Drupal.

- composer.json
- composer.lock
Applies the patch for [Drupal core bug 3042889](https://www.drupal.org/project/drupal/issues/3029219).
That bug did not correctly recognize that a new translation was
at the beginning of its moderation state cycle, instead conflating
the moderation history of the original language content with that
of the new translation. This resulted in failed saves because of
rejection of what should have been accepted as valid state transitions.
The Drupal core team seems reluctant to accept our patch (or even
acknowledge that this is a bug), so we have no choice but to move on
and just apply the patch ourselves.
Closes #475
> Fix Drupal moderation handling of new translations

- docroot/profiles/custom/cgov_site/cgov_site.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_form_display.paragraph.body_section.default.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_util/cgov_util.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_util/cgov_util.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_util/src/CgovFormTools.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/011_coping_feelings.content.yml
TIcket #835. Ability to limit text formats
* Adds and enables the Cgov Utility module
* Limits article WYSIWYG fields to allowed text formats
* Updates row size for Article body content field
> Add and enable Cgov Utility form tools service. Limit article text formats

- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/formControls/formControls.js
Closes #1326 . 
Our formControls.js library is modifying select elements in a way that conflicts with Drupal's own generated select menus in content preview mode. This PR adds an extra :no selector to our library to prevent the conflict.
> Add blacklist selector for preview mode select menus

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/ckeditor/Ckeditor.scss
Closes #1238 . This is a simple fix that a) resets ul display override and b) gives a margin-left to li elements.
> Add rule to reset ULs back to normal

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/field--field-article-body.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/paragraph--body-section.html.twig
In the new system, OTP is drawn through twig. In the old system, it's done by NCI.page.js. Migrated articles may not be correctly transformed into the new paragraphs and instead be dumped raw into a  single paragraph. That edge case needs to be handled. NCI.page.js still runs and will correctly draw the OTP when the twig template fails to do so.
ODE: http://ncigovcdode82.prod.acquia-sites.com
> OTP migration edge case handling.

- composer.json
- docroot/lib/CgovPlatform/Tests/CgovSchemaExclusions.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/RolesTest.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/TestKernelTest.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/WorkflowTest.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/ApiTest.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/PDQCancerSummaryTest.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/tests/src/Functional/ApiTest.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/tests/src/Functional/PDQDrugSummaryTest.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/tests/src/Functional/ApiTest.php
- docroot/profiles/custom/cgov_site/tests/src/Functional/CgovSiteTest.php
- docroot/profiles/custom/cgov_site/tests/src/Functional/PdqNodeTypeTest.php
Closes #1367 
Adds the schema exclusion library. Currently the list of items to exclude is empty as they will be added  in the necessary modules PR.
> Add Cgov Schema Exclusion library.

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/paragraph--cgov-column-two.html.twig
Closes #1444 :
Removed the flex-columns class which doesn't exist on prod
> Ticket-1444: two column list display is not appearing correctly

- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogTopicTitle.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/block--cgov-blog-topic-title.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/blog_macros.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/node--cgov-blog-series--full.html.twig
* Draw topic name as part of title on category pages
* Moved series title block into blog_macros.twig
> (#1534) Blog Categories - Page Title is not pulling category name

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/PageOptionsManager.php
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/blogSeries/BlogSeries.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/homelanding/Homelanding.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block/page_options/block--page-options.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/node--cgov-blog-series--full.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/page--cgov-blog-series.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/node--cgov-home-landing--full.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/pdq/node--pdq-drug-information-summary--full.html.twig
Closes #1482 .
Page options not showing up for certain content types.  
- Added content types to page options manager
- fixed positioning of page options on homelanding pages
- added base template for DIS;  twig template was completely missing so added a rough template as a placeholder until work on ticket #1516 is completed
> Page options issues

- composer.json
- composer.lock
- docroot/profiles/custom/cgov_site/cgov_site.info.yml
- docroot/profiles/custom/cgov_site/config/install/purge.logger_channels.yml
- docroot/profiles/custom/cgov_site/config/install/purge.plugins.yml
- docroot/profiles/custom/cgov_site/config/install/purge_queuer_coretags.settings.yml
- docroot/profiles/custom/cgov_site/config/install/system.performance.yml
- docroot/sites/default/settings/default.local.settings.php
This PR sets up the initial caching/purge configurations for Acquia environments.
- Adds Acquia Purge module to composer.
- Enables acquia_purge and dependencies in install profile.
- Configures purgers and cache config.
This PR enables/utilizes features to handle configuration that is updated from a core or contrib module. 
- Enable features
- Configure updated feature bundle (cgov_util)
- Export configs for cgov_cache module
- Run a fresh `blt setup` and confirm purge is installed and configured.
Add the following to your docroot/sites/default/settings/local.settings.php:
```
$config['system.performance']['cache']['page']['max_age'] = 0;
```
(*NOTE: this has been added to the default.local.settings.php for new environment setups*)
> Cache Purging

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-linkedin-handle.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-scientific-publications.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-title.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-twitter-handle.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/node--cgov-biography--full.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_profile-panel.scss
Closes #1470 , #1469 , #1471 .
(#1470) Biography: multiple organizations with shorter
names moving to single line
(#1471) Biography- spacing between multiple titles
regrouped titles to be like orgs applying margin to bottom of group.  New grouping and spacing approved by design
(#1469) Biography: disable external link icons in top profile card
> Biography page display issues

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-linkedin-handle.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-scientific-publications.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-title.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-twitter-handle.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/node--cgov-biography--full.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_profile-panel.scss
(#1470) Biography: multiple organizations with shorter
names moving to single line
(#1471) Biography- spacing between multiple titles
regrouped titles to be like orgs applying margin to bottom of group
Biography page fixes
> (#1469) Biography: disable external link icons in top profile card

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/MainNav.php
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/page--cgov-blog-post.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/page--cgov-blog-series.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cthp/page--cgov-cthp.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/page--cgov-home-landing.html.twig
Mobile menu was not triggering due to improper markup concerning the `<div class="headroom-area">` element. Also fixed an issue where the site footer had a double `<footer>` wrapper, which is invalid markup.
Closes #1560 
Closes #1620
> (#1560) Mobile Menu Not Triggering

- composer.json
- composer.lock
- docroot/sites/default/default.settings.php
Closes #1612 
Replaces `drupal/core` version contraint with `webflo/drupal-core-require-dev` in `composer.json` in order to resolve circular dependencies for future core updates.
> (#1612) Update Drupal core to 8.7.0 release

- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/FixHomeUrlAliasOutboundPathProcessor.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/100_home.content.yml
* A "homepage" should appear at when you go to http://ncigovcdode123.prod.acquia-sites.com/
* The http://ncigovcdode123.prod.acquia-sites.com/user/login url should still work
* When you edit the English home site section and change the landing page, http://ncigovcdode123.prod.acquia-sites.com/ should point to the new page.
* NOTE: You *should* change the existing landing page's SiteSection/Pretty to reflect it is not the homepage first. This update will not change the Landing Page's site section, nor pretty url. All it does is makes this page the system's front page, and makes sure the URLs pointing to that node display as /.
* Aliases for the content has a site section of "Home" and an empty pretty url will still be generated as `/-0`. This should not show up on the front-end. Places to …
> (#1504) Make a homepage yml and make it work

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/cthp/CTHP.scss
Closes #1606 .
Moved one piece of this ticket onto #1589 where by DOM manipulation can be avoided in exitDisclaimer.js and handled in the templates for external feature cards.
Styles that were previously targeted to . cgvcancertypehome and are now scoped via CTHP stylesheet.
ODE: http://ncigovcdode129.prod.acquia-sites.com/types/breast
> (#1606) Content Type specific references to be updated for CTHP

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/paragraph--cgov-internal-link--cthp-research-card-list-item.html.twig
* Page title instead of short title (RIP) on CTHP Cancer Research Card
* Closes #1675
> (#1675) Use page title in Cancer Research Lists

- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/pdq_drug_information_summary.module
* PDQ DIS also uses shared body field, but needs raw_html format
* Add check for PDQ DIS form to constrain body to raw_html format
* This allows all other shared body fields to have full_html
* Closes #1806
> (#1806) Shared body field should use Full WYSIWYG

- acsf-convert/files/docroot/sites/default/acsf.settings.php
- acsf-convert/files/docroot/sites/g/apc_rebuild.php
- acsf-convert/files/docroot/sites/g/settings.php
- acsf-convert/files/docroot/sites/g/sites.inc
- acsf-convert/files/docroot/sites/sites.php
- acsf-convert/files/hooks/common/post-db-copy/000-acquia_required_scrub.php
- docroot/sites/default/settings.php
`drush --include=docroot/modules/contrib/acsf/acsf_init acsf-init-verify` failed because updates of the module can bring along file changes we need to apply to our acsf-convert folder.
> Fixed file changes after ACSF module update

- docroot/robots.txt
- scripts/pipelines/build_artifact
- scripts/pipelines/setup_env
- Forced robots.txt to always disallow. CDN will allow under very
special circumstances.
- Removed modification to blt.yml in setup_env. ci.blt.yml will exist
and therefore this was no longer needed.
- Added in the dirty check in build_artifact now that we do not
modify the blt.yml file. This will prevent untracked changes being
created during the build process from showing up in our list.
> Config Changes

- blt/01dev.blt.yml
- blt/01test.blt.yml
- blt/blt.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_form_display.node.cgov_article.default.yml
- cgov_article was being called out as out of sync,
but it had not been modified since we enabled
features. I re-exported it, as it was at least
behaving that way locally.
- Error with cgov_article & cgov_application_page
is still occurring on AH environments. Features
diff indicates no differences, and local dev
environment do not show any errors.
- Enabled config overrides as to not break the
system too much.
> Minimized Features Out of Sync Errors

- docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/cgov_biography.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/cgov_cancer_center.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/cgov_cancer_research.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovConfigOverrider.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/WorkflowTest.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Traits/CGovWorkflowAttachmentTrait.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/cgov_cthp.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_event/cgov_event.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/cgov_press_release.install
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.install
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/pdq_core.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/PDQConfigOverrider.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/tests/src/Kernel/WorkflowTest.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/pdq_drug_information_summary.install
- tests/behat/features/ContentWorkflow.feature
- tests/behat/features/PDQ.feature
- tests/behat/features/Translation.feature
Overriding workflow config for applying workflow to entities so that it ignores all config import/export settings.
Commit 1:
1. Provides a ConfigOverride class for cgov_core and pdq_core. 
2. Overrides configuration for workflow `['type_settings']['entity_types']` which are removed from exports as they create dependency chains we do not want. 
3. Handles all 3 workflows (based on the most reusable patterns I could find). 
Commit 2:
1. Removes workflow assignment from install hooks on modules. 
2. Moves workflow helper function to custom trait for tests.
Commit 3: 
1. Updates existing behat tests to actually run.
2. Adds new tests for coverage of workflows across all ctypes.
3. Fixes issue w/ Advanced Editor not being able to use workflow on blocks.
1. Right now this is built so CGov …
> NCI-000: ConfigOverrider for Workflows

- blt/src/Commands/SlevenCommand.php
- hooks/common/post-code-deploy/post-code-deploy.sh
- hooks/common/post-code-update/post-code-update.sh
Deployments are failing, and I believe it is because memcache is holding onto the information after the sql-drop called in the artifact:install. A drush cr seems to fix it.  There may be a better way, and maybe it is calling memcache directly.
> (#2067) Fix issue with memcache and drupal install.

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/CmsProtectionSubscriber.php
- Routes are still protected with rest protection
requirements. (Basic auth, etc)
> Removed CMS Protection from pdq API routes.

- docker/web/runtime/php.ini
- docker/web/runtime/php_apache2.ini
- docker/web/runtime/php_cli.ini
- docroot/profiles/custom/cgov_site/cgov_site.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/cgov_redirect_manager.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/cgov_redirect_manager.links.menu.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/cgov_redirect_manager.links.task.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/cgov_redirect_manager.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/cgov_redirect_manager.routing.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/cgov_redirect_manager.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/CgovImporterService.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/Form/RedirectImport.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/Plugin/QueueWorker/RedirectManagerQueueWorker.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/tests/src/Unit/CgovImporterServiceTest.php
- Initial commit of Redirect Manager for Cgov
- Implements administration form for uploading, saving and queueing up file.
- Implements QueueWorker to process the newly created queue items on cron
- Implements Service for managing imports (taken and modified from path_redirect_import)
- Uploads PHP upload_max_filesize to 20MB on local docker (set to 256M on Acquia)
1. Visit the administration page for importing redirects: `/admin/config/search/cgov-redirect-manager`
2. Upload your CSV file of redirects. (2 columns, no headers)
1. This uploads your file to the files-private directory.
2. This creates a new queue item to be processed: cgov_redirect_manager_queue_worker
3. The queue item will be picked up on the next cron run. 
4. Manual Override: 
1. Manually execute a `drush cron`  OR
2. A …
> NCI-000: Initial commit for CGOV Redirect Manager.

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
Closes #2083 
*  Adds a hook alter to disable Acquia Connector Toolbar for non 'site_admin" users. 
http://ncigovcdode207.prod.acquia-sites.com/
To test, log in as siteadmin and compare to any other user (admin, auth0r, etc..).
> (#2083) Add hook alter to disable Acquia Connector Toolbar 

- composer.json
- composer.lock
- docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/metatag.metatag_defaults.node__cgov_application_page.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/metatag.metatag_defaults.node__cgov_article.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_post.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_series.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/metatag.metatag_defaults.node__cgov_cancer_center.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/metatag.metatag_defaults.node__cgov_cancer_research.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.front.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/metatag.metatag_defaults.node__cgov_cthp.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_home_landing.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_mini_landing.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/metatag.metatag_defaults.media__cgov_infographic.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/metatag.metatag_defaults.node__cgov_press_release.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.media__cgov_video.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.node__cgov_video.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/metatag.metatag_defaults.node__pdq_drug_information_summary.yml
(#2123) Update metatag defaults to include title metatag
(#2155) Update og_title metatag on home pages (for use in social media links)
(#2125) Fix browser title on PDQ CIS pages to show full page title
> (#2123, #2125, #2155) Metatag updates

- docroot/sites/settings/cgov_core.settings.php
Closes #2219 
Note this still leaves an outstanding issue where the sitemap has a /espanol link even if there is no translated homepage.
> (#2219) Fixes sitemaps on microsites.

- docroot/lib/CgovPlatform/Tests/CgovSchemaExclusions.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/metatag.metatag_defaults.node__cgov_application_page.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/metatag.metatag_defaults.node__cgov_article.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/metatag.metatag_defaults.node__cgov_biography.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_post.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_series.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/metatag.metatag_defaults.node__cgov_cancer_center.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/metatag.metatag_defaults.node__cgov_cancer_research.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.403.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.404.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/metatag.metatag_defaults.node__cgov_cthp.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_home_landing.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_mini_landing.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/metatag.metatag_defaults.media__cgov_infographic.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/metatag.metatag_defaults.node__cgov_press_release.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.media__cgov_video.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.node__cgov_video.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/metatag.metatag_defaults.node__pdq_drug_information_summary.yml
- docroot/profiles/custom/cgov_site/translations/cgov_site.es.po
#2221, #2222: Fixes metatags so they all get set on Spanish pages
#2223: Lowercasing "del" in Spanish organization name translation
#2250: Adding content-language metatag for media items
#2078: 403 and 404 page browser titles
> (#2221, #2222, #2223, #2250, #2078) Spanish metatags, browser title org append, media content language, 403 and 404 page browser titles

- docroot/profiles/custom/cgov_site/modules/custom/cgov_file/cgov_file.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_file/src/EventSubscriber/DirectFileDownloadSubscriber.php
- Allows for better control of downstream caching in Akamai
- Allows for cache invalidation based on media on all
external cache layers
Closes #2251
> (#2251) Added caching headers to files

- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/Plugin/rest/resource/PDQResource.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/ApiTest.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/Plugin/rest/resource/PDQResource.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/src/Plugin/rest/resource/PDQResource.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/tests/src/Functional/ApiTest.php
Copy only the ticket/2249-stuck-pdq-drafts fixes from #2278.
(Replaces #2278)
Replace the use of the flawed entity query API with a direct call to get the latest revision
Explicitly set the revision_translation_effective flag when publishing
Add missing @throws statements
Replace t(...) with $this->t(...)
Closes #2249
> (#2249) Prevent PDQ content from being stuck as drafts

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/CmsProtectionSubscriber.php
- Throwing a 403 exception on the saml_login page was not good
enough to be considered the login route. Hopefully this will stop
saml_login from redirecting to saml_login when SSO user is not
in Drupal.
Try number 2
> (#2320) Need to allow access denied routes

- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/Plugin/rest/resource/PDQResource.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/Plugin/rest/resource/PDQResource.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/src/Plugin/rest/resource/PDQResource.php
* Assign `$nid` defensively in case the 'nid' index is not present in `$summary`
* Allow simultaneous deletion of multiple temporary publish preview nodes
* Closes #2318 
* Closes #2319
> PDQ Restful API patches

- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.install
Add the 'translate cgov_blog_topics taxonomy_term' permission to
the site_admin role.
Closes #2407
> (NCIOCPL#2407) Site Admin Can't Translate Blog Topic.

- docroot/modules/custom/app_module/app_module.services.yml
- docroot/modules/custom/app_module/config/schema/app_module.schema.yml
- docroot/modules/custom/app_module/src/Annotation/AppModulePlugin.php
- docroot/modules/custom/app_module/src/AppModuleInterface.php
- docroot/modules/custom/app_module/src/Entity/AppModule.php
- docroot/modules/custom/app_module/src/Form/AppModuleForm.php
- docroot/modules/custom/app_module/src/Plugin/AppModulePluginManager.php
- docroot/modules/custom/app_module/src/Plugin/Field/FieldFormatter/AppModuleReferenceFieldFormatter.php
- docroot/modules/custom/app_module/src/Plugin/Field/FieldWidget/AppModuleReferenceSelectWidget.php
- docroot/modules/custom/app_module/src/Plugin/app_module/AppModulePluginBase.php
- docroot/modules/custom/app_module/src/Plugin/app_module/AppModulePluginInterface.php
- docroot/modules/custom/app_module/tests/modules/app_module_test/config/install/app_module.app.test_app_module.yml
- docroot/modules/custom/app_module/tests/modules/app_module_test/src/Plugin/app_module/TestAppModulePlugin.php
- docroot/modules/custom/app_module/tests/src/Functional/AppModuleEntityTest.php
- docroot/modules/custom/app_module/tests/src/Functional/AppModuleFieldBrowserTestBase.php
- docroot/modules/custom/app_module/tests/src/Functional/AppModuleReferenceFieldFormatterTest.php
- docroot/modules/custom/app_module/tests/src/Functional/AppModuleReferenceSelectWidgetTest.php
- This implements the necessary classes to create app
module plugin implementations. It does not contain
any code to make them do anything other than to
display a label. (e.g. no rendering, no fetching data)
- Includes the changes to tests to test the items.
Closes #2417
> (#2417) Create App Module Plugin System

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/NavItem.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/SectionNav.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block/section_nav/block--cgov-section-nav.html.twig
ODE: ncigovcdode268.prod.acquia-sites.com
Closes #2206 
Closes #2315 
Note: Acceptance Criteria are on the individual tickets.
- Adds the node bundle ID to the nodes cache tags. e.g:
- cgov_article:full 
- cgov_article:all-view-modes 
- cgov_blog:all-view-modes 
- Adds the Section NavRoot ID to the Section Nav blocks cache tags. e.g:
-  site_section:11844
- Adds logic to invalidate a given Section Nav root ID -- under the right circumstances.
-  When relevant Site Section Fields are updated
-  When Site Section or Pretty URL changes on a node 
- Cleans up / extracts the term re-save logic into a function.
> (#2315, #2206) - Add CT cache tags, Update Site Section tag logic

- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.module
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/field--field-article-body.html.twig
* Logic for correct markup on single-section article pages
* Move preprocessor functions to cgov_article
* Closes #2456
> (#2456) Fix schema.org markup on non-FAQ pages

- composer.json
- composer.lock
- docroot/profiles/custom/cgov_site/cgov_site.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.links.action.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.routing.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Form/CgovVocabManagerForm.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Manager/CgovVocabManager.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Routing/RouteSubscriber.php
* Implements cgov_vocab_manager to provide an updated Vocabulary Management Experience.
* Adds core patch to allow default term overview pages to render and not blow up.  
Rebuild the Taxonomy Vocabulary Overview Page: 
* The Vocab Overview page should display only one level of terms at a time. 
* Each term on the page should have a new button: “Manage Children” if the term has children. 
* The user should have the same functionality as the current Taxonomy Vocab overview page:
* Edit/Create/Delete/Reorder (based on perms)
* Once a user clicks on “Manage Children” of a term:
* The page reloads with the next level of children. 
* The breadcrumb is updated with the Parent Path so that there is a clear hierarchy visible on the page 
* Each term on the page should have a new button: “Manage …
> [POC] NCIOCPL-000: Prototype for CGov Vocab Manager.

- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
Include the entity alias as a trigger for section cache tag invalidation. 
Closes #2462
> (#2462) Include the entity alias as a trigger for section cache tag invalidation.

- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/900_cgov_site_section.content.yml
Additions for the following PR: https://github.com/NCIOCPL/cgov-digital-platform/pull/2448
* Updated logic for invalidating the cache tags to account for additional scenarios.
Ultimately: A Section Nav Item (site section term) modification should take effect immediately on all pages / blocks that render it.
**ODE:** ncigovcdode272.prod.acquia-sites.com
> Modify logic to check for all rendering nav roots.

- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
Closes #2493
ODE: ncigovcdode279.prod.acquia-sites.com
> (#2493) Include field_levels_to_display as a trigger for cache tag clearing.

- docroot/modules/custom/app_module/app_module.module
- docroot/modules/custom/app_module/src/AppModuleRenderArrayBuilder.php
- docroot/modules/custom/app_module/src/AppModuleRenderArrayBuilderInterface.php
- docroot/modules/custom/app_module/src/PathProcessor/PathProcessorAppModule.php
- docroot/modules/custom/app_module/src/Plugin/app_module/AppModulePluginBase.php
- docroot/modules/custom/app_module/src/Plugin/app_module/AppModulePluginInterface.php
- docroot/modules/custom/app_module/src/Plugin/app_module/MultiRouteAppModuleBuilderBase.php
- docroot/modules/custom/app_module/src/Plugin/app_module/MultiRouteAppModuleBuilderInterface.php
- docroot/modules/custom/app_module/src/Plugin/app_module/MultiRouteAppModulePluginBase.php
- docroot/modules/custom/app_module/tests/modules/app_module_test/src/Plugin/app_module/TestAppModulePlugin.php
- docroot/modules/custom/app_module/tests/src/Functional/AppModuleRouteTest.php
- docroot/modules/custom/app_module/tests/src/Unit/PathProcessorAppModuleTest.php
- Added in scaffolding for modules to participate in the
hook_page_attachments_alter hook and hook_tokens_alter
- Added a method to identify what tokens an app module
would use. Implemented hook_tokens_alter to filter
out calls to app module based on available tokens.
- Added additional app_module parameters to the request
query params in order to support these hook events,
as hooks run outside of our FieldFormatter, which is
what actually renders the app module.
- Updated tests for the path processor to validate our
additional request parameters.
- NOTE: There is an issue with testing this scaffolding
as our .module hooks are not being registered and
thus are not firing during a Functional test.
Co-authored-by: Sarina Padilla <sarinapadilla@user.noreply.github.com>
> (#2562) Metadata support for App Modules

- composer.lock
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/app_module/cts/clinical-trial.html.twig
- Update  nciocpl/clinical-trial-search-client.php
- Uncomment references for ContactName and ContactEmail properties.
- Replace 'is defined' condition with 'is not empty'.
Closes #2571
> (#2571) Display trial site's contact phone and email 

- docroot/modules/custom/app_module/src/Plugin/app_module/MultiRouteAppModuleBuilderBase.php
- docroot/modules/custom/cgov_cts/cgov_cts.services.yml
- docroot/modules/custom/cgov_cts/src/MultiRouteBuilders/CTSAdvancedSearchBuilder.php
- docroot/modules/custom/cgov_cts/src/MultiRouteBuilders/CTSBuilderBase.php
- docroot/modules/custom/cgov_cts/src/MultiRouteBuilders/CTSDefaultBuilder.php
- docroot/modules/custom/cgov_cts/src/MultiRouteBuilders/CTSResultsBuilder.php
- docroot/modules/custom/cgov_cts/src/MultiRouteBuilders/CTSViewDetailsBuilder.php
- docroot/modules/custom/cgov_cts/src/Plugin/app_module/ClinicalTrialsSearchAppModulePlugin.php
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/app_module/cts/app-module--cgov-cts-app--cgov-cts-app-module-plugin--advanced-search.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/app_module/cts/app-module--cgov-cts-app--cgov-cts-app-module-plugin--default.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/app_module/cts/app-module--cgov-cts-app--cgov-cts-app-module-plugin--results.html.twig
(#2580) Update CTS Advanced Search metatags
* Update metatag overwrites for CTS Advanced Search
* Closes #2580
(#2573) Update CTS page metadata
* Create builder base class for CTS pages
* Update default & create advanced/results builders for CTS pages
* Set build arrays, alter page attachments, and overwrite metatag tokens
* Update CTS App Module Plugin with all CTS page builders
* Update services file with all CTS page builders
* Create/update twig templates for CTS pages
* Closes #2573
> CTS Metatags

- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/dictionaryService/index.js
- Add 'notset' to the list of dictionaries to validate against.
- Make validation case-insensitive.
- File formatting changes imposed by new code sniffer rules.
Closes #2614
> (#2614) Fix lookup for terms in the 'NotSet' dictionary.

- FrontendGlobals.json
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/floatingDelighter/README.md
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/floatingDelighter/rules.js
* Removes floating delighter for any path starting with /rare-brain-spine-tumor/espanol
* Enables delighters in default content.
Closes #2620
> (#2620) Turn off floating delighter on Spanish  NCI-Connect pages

- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/site-banner.content.yml
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/config/install/cgov_common.settings.yml
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/config/schema/cgov_common.schema.yml
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/blue/entrypoints/Blue.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/green/entrypoints/Green.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/purple/entrypoints/Purple.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/theme-settings.php
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_language_bar.scss
- Add has_translations as a theme setting.
- Modify CSS to control language bar visibility based
on has_translations setting.
Closes #2625 
Closes #2640
> (#2625) Add translations as a theme option.

- docroot/profiles/custom/cgov_site/cgov_site.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.features.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.menu.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.routing.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/config/install/cgov_mail.settings.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/config/schema/cgov_mail.schema.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/src/Controller/MailAPIController.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/src/Form/MailSettingsForm.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/src/Plugin/Mail/CgovMailLogger.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/email-form.content.yml
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_errorPage.scss
- docroot/sites/settings/cgov_core.settings.php
* Adds and enables the cgov_mail module.
* Adds email-form.content.yml to cgov_yaml_content module.
* Creates a controller to handle e-mail forms.
* Enables the re-rerouting of e-mails to log on lower tiers.
Closes #2466
**ODE:** http://ncigovcdode319.prod.acquia-sites.com
**Form:** http://ncigovcdode319.prod.acquia-sites.com/contact/email-us
**DB Log:** http://ncigovcdode319.prod.acquia-sites.com/admin/reports/dblog
**Configuration:** http://ncigovcdode319.prod.acquia-sites.com/admin/config/cgov_mail/settings
**ODE:** http://ncigovcdode320.prod.acquia-sites.com
**Form:** http://ncigovcdode320.prod.acquia-sites.com/contact/email-us
**Configuration:** http://ncigovcdode320.prod.acquia-sites.com//admin/config/cgov_mail/settings
- On the ODE's e-mails have been received 30min+ after being …
> (#2466)  Add the cgov_mail module.

- composer.json
- composer.lock
Fix mismatch in variable name (`$values` -> `$vals`).
Fixes issue #2731 
Fixes issue #2743
> (#2743) Fix typo in purge patch

- blt/src/Commands/UsersCommand.php
> (#2746) Add missing 'use' statement for BltException class.

- simplesamlphp/config/authsources.php
- Correct the IDP entity ID for the ACSF test tier.
- Make the selection of IDP for ACSF dev tier explicit.
> (#2291) Correct entity ID for Test Tier IDP

- docroot/profiles/custom/cgov_site/config/install/adobe_dtm.settings.yml
- Updated Adobe DTM config to point to Extension Development Property
This is needed going forward now that Cancer.gov is using the new Event-Driven Data Layer analytics.
> (#2791) Update Adobe DTM config

- composer.json
- composer.lock
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.links.menu.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.permissions.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Routing/RouteSubscriber.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc
* (#2810) Update pathauto package to 1.6
- This is to support the 8.9 upgrade
* (#2814) Fixed Error in URL Generation
- There were a few conditions where is a term were deleted from the system and still had associated entities it would break all URL generation. Added guards and logging.
* (#2784) Expose Pathauto Bulk Generate
- Allow site admins to rebuild aliases when they change site sections.
Closes #2810
Closes #2814
Closes #2784
> (#2810, #2814, #2784) Multiple URL Management Updates

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/glossary/glossary.js
* Update setting basepath and alt language basepath values correctly:
* Add preceding slash if not there (IE fix)
* Closes #2837
> (#2837) Fix basepath and altlangbasepath in IE

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/mainNav/mobilemenu.js
Update the mobile menu to handle spanish links correctly, adding .current-page instead of .contains-current
> Hotfix: Spanish menu items not getting current page designation

- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoCarousel/video-carousel.js
Closes #2928 .
Fix for injected markup which was causing mobile controls for video carousel to be hidden.
**Issue:** Playlist controls for video carousel (playlist of more than 3 videos) were not appearing at mobile and tablet breakpoints with the updates from release v1.2.0
Also changed alt attribute on buttons to aria-label for proper labeling for accessibility
ODE for testing:
http://ncigovcdode392.prod.acquia-sites.com/about-cancer/coping/feelings
http://ncigovcdode392.prod.acquia-sites.com/test/video-carousel-controls
> Bugfix: Video Carousel mobile/tablet controls

- docroot/.htaccess
- patches/drupal-scaffold/htaccess.acsf.patch
- patches/drupal-scaffold/htaccess.hsts.patch
- patches/drupal-scaffold/htaccess.https.patch
- Remove 403 for non HTTPS access attempt, simply redirect to HTTPS. This will enforce HTTPS in all environments, regardless of domain.
- Update line numbers for file offsets occuring after .htaccess.https.patch.
Close #2989
> (#2989) Require HTTPS to access the site.

- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/README.md
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/rest.resource.pdq_cis_api.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/drush.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.install
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/Commands/OrphanCleanupCommands.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/OrphanCleanup.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/Plugin/rest/resource/PDQResource.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/ApiTest.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/README.md
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/config/install/rest.resource.pdq_api.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/drush.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/pdq_core.install
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/pdq_core.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/Commands/RevisionPrunerCommands.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/Plugin/rest/resource/PDQResource.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/RevisionPruner.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/tests/src/Kernel/CleanupTest.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/src/Plugin/rest/resource/PDQResource.php
Addresses some of the issues raised by #2815 but not necessarily all of them (so not using the magic "closes" phrase for that ticket in this comment). Also takes care of #2630.
Adds:
* new service to identify and remove older PDQ content node revisions
* new service to drop orphaned summary section paragraph entities/revisions
* new `drush` commands to use the new services
* new REST API endpoints
* new phpunit tests
* correct revision timestamp and user
Closes #2630
> Prune PDQ CIS revisions

- docroot/modules/custom/cgov_glossary/cgov_glossary.install
- docroot/modules/custom/cgov_sitewide_search/cgov_sitewide_search.install
- docroot/profiles/custom/cgov_site/cgov_site.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.install
Two-fer.
#3022 Disables the legacy Glossary App module.
#3021 Disables the legacy Site Wide Search App module.
Closes #3022 
Closes #3021
> Disable legacy glossary and sitewide search app modules

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
Closes: #2091
ODE: https://ncigovcdode425.prod.acquia-sites.com/
Fixed the incorrect Tooltip for External Links as requested.
> (#2091) Removes incorrect Tooltip for External Links

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php
http://ncigovcdode425.prod.acquia-sites.com
Closes: #3089 
Fixed - The CgovCoreTools is incorrectly referencing the exception class.
> (#3089) CgovCoreTools is incorrectly referencing the Exception class

- blt/blt.yml
- blt/ci.blt.yml
- blt/src/Blt/Plugin/Commands/Tests/OverrideValidateAllCommand.php
- blt/src/Blt/Plugin/Commands/Tests/ProfileDrupalCheckCommand.php
- Added an override BLT command for validate:all to run our new
ProfileDrupalCheckCommand that calls drupal-check on our profiles
folder.
Closes #2927
> (#2927) Fix Deprecation Check

- composer.json
- composer.lock
This is a tricky one. The migration stuff in the profile needs to be removed as it is now outdated and would most likely fail since content types have changed, and the original sites no longer exist to pull images and files from. HOWEVER, loading the site sections for ODE content IS migrate and the cgov_migrate code. So this all still references migrate_file, and we need to bump the version, however we have no real way to test. So as long as browser tests still work and nothing else breaks, we are going to do this update untested otherwise.
Closes #3122
> (#3122) Updated the migrate_file module

- composer.json
- composer.lock
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/user.settings.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/config/install/simplesamlphp_auth.settings.yml
Updates drupal/simplesamlphp_auth to v3.2
- Remove default_langcode from cgov_saml_auth_config to match changes in simplesamlphp_auth.
- Eliminate false positives for feature diffs `user.settings register` in some scenarios.
Closes #3124
> (#3124) Update simplesamlphp_auth to 3.2

- docroot/modules/custom/cgov_adobe/cgov_adobe.info.yml
- docroot/modules/custom/cgov_adobe/cgov_adobe.links.menu.yml
- docroot/modules/custom/cgov_adobe/cgov_adobe.module
- docroot/modules/custom/cgov_adobe/cgov_adobe.permissions.yml
- docroot/modules/custom/cgov_adobe/cgov_adobe.routing.yml
- docroot/modules/custom/cgov_adobe/config/install/cgov_adobe.settings.yml
- docroot/modules/custom/cgov_adobe/config/schema/cgov_adobe.schema.yml
- docroot/modules/custom/cgov_adobe/src/Form/CgovAdobeSettingsForm.php
- docroot/modules/custom/cgov_adobe/tests/src/Functional/CgovAdobeRenderTest.php
- docroot/profiles/custom/cgov_site/cgov_site.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
ODE: ncigovcdode432.prod.acquia-sites.com
- This is to remove adobe_dtm, which does not support Drupal 9.
- This borrows from some of the logic, what is necessary for our requirements.
- We addeed a config:cgov_adobe.settings cache tag to the build array, so updating the analytics config will invalidate all pages and the Drupal cache. I.E. No longer a need to drush cr and the like when the config is updated. This did not exist previously.
- This also enables cgov_adobe, copies the launch URL from the adobe_dtm config, and disables adobe_dtm.  
- THIS DOES REQUIRE AN SUBSEQUENT RELEASE TO REMOVE THE adobe_dtm MODULE FROM COMPOSER!
Closes #3121
> (#3121) Create new Adobe Launch module

- composer.json
- composer.lock
This removes the module from the codebase -- it is assumed this will be deployed immediately after release 1.2.14.
Closes #3180
> (#3180) Remove Adobe DTM Module

- blt/blt.yml
- blt/src/Blt/Plugin/Commands/SlevenCommands.php
- hooks/common/post-code-deploy/post-code-deploy.sh
- hooks/common/post-code-update/post-code-update.sh
- Created new BLT command to load the front-end globals config. The config path is set in the blt.yml file under `cgov:front_end_globals_file`, but this should not really ever change.
- Added our command to `blt cgov:reinstall` so now that is handled automatically.
- Updated both post-code-update and post-code-deploy to use the new command
>**_NOTE:_** I removed the front-end globals reloading when the $PRESERVE_ON_REDEPOY flag is set to true. This is because these globals act as content, or else they would be packaged as features. So it is not appropriate to reset these configurations on each load from what is in the codebase.
Closes #3197
> (#3197) Load front-end globals on reinstall

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/blue/styles/sprites/_svg-sprite.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/connect/styles/sprites/_svg-sprite.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/green/styles/sprites/_svg-sprite.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/purple/styles/sprites/_svg-sprite.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/webpack.config.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/sprites/sprite-template.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/webpack.base.config.js
This fixes an issue in the develop branch where Sprite paths are incorrect for microsite variants.
ODE: http://ncigovcdode451.prod.acquia-sites.com/AH_VIEW
Closes #3275
> (#3275) Fix theme variant sprite path.

- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/911_cct_chatbot_pages.content.yml
- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/deepLinkPatch/deepLinkPatch.js
This fix rewrites (via JS) any #link/_123 style links in content.
This hack should be removed once the PDQ content is no longer publishing anchors in this old format.
ODE: http://ncigovcdode453.prod.acquia-sites.com/AH_VIEW
Closes #3288
> (#3288) Hack to fix legacy links in PDQ

- docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc
- Updated cgov_tokens:cgov-trans-org-name replacement value from "National Cancer Institute" to "NCI"
ODE: http://ncigovcdode455.prod.acquia-sites.com
Closes #3299
> (#3299) Update Browser Title

- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/svpc_liver-cancer-causes-risk-factors-and-prevention.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/svpc_liver-cancer-diagnosis.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/svpc_liver-cancer-treatment.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/svpc_what-is-liver-cancer.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/z042_liver-cthp.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_form_display.node.pdq_cancer_information_summary.default.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_view_display.node.pdq_cancer_information_summary.cthp_guide_card_list_item.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_view_display.node.pdq_cancer_information_summary.default.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_view_display.node.pdq_cancer_information_summary.full.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_view_display.node.pdq_cancer_information_summary.teaser.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.field.node.pdq_cancer_information_summary.field_pdq_intro_text.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.field.node.pdq_cancer_information_summary.field_pdq_is_svpc.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.field.node.pdq_cancer_information_summary.field_pdq_suppress_otp.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.storage.node.field_pdq_intro_text.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.storage.node.field_pdq_is_svpc.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.storage.node.field_pdq_suppress_otp.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.install
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.module
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/Plugin/rest/resource/PDQResource.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/ApiTest.php
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/pdq/PDQ.js
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/pdq/node--pdq-cancer-information-summary--full.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/pdq/node--pdq-cancer-information-summary--hhs-syndication.html.twig
Three fields have been added to the pdq_cancer_information_summary content type to support the Single View Patient Content project.
- A new flag (field_pdq_is_svpc) indicating that the summary is an SVPC summary (Story: Update Cancer Information Summary content type with SVPC field #3231)
- A new flag (field_pdq_suppress_otp) indicating that the On This Page links section should not be displayed (Story: Update Cancer Information Summary content type with Hide On This Page field #3230)
- A new raw HTML field (field_pdq_intro_text) to be displayed if present at the top of the page for the summary, following the title but preceding the summary sections (and the On This Page links if those are present) (Story: Update Cancer Information Summary content type with Intro Text field #3229)
In …
> Add support for the SVPC project

- docroot/sites/settings/cgov_fast_404.settings.php
Change for #3450 to support https://github.com/NCIOCPL/cgov-digital-platform-maintenance-scripts/issues/1. Simply adds a meta tag for generator to the fast 404 template HTML.
Closes #3450.
> Add a generator tag to indicate that a 404 response comes from fast 404

- docker/web/Dockerfile
Installs the NIH root certificate from ocio.nih.gov so that SSL calls from within docker image work on VPN.
Closes #3463
> (#3463) Install NIH root certificates in docker image

- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/ncids-common.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/home-landing/home-landing-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/__tests__/usa-footer.test.ts
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/usa-footer.ts
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/layout/regions/ncids/region--ncids-sidenav.html.twig
Closes #3608 .
Closes #3594 .
Closes #3528 .
Closes #3603 .
- added class `nci-no-print` to sidenav container; added no-print partial to ncids-common
- updated analytics naming for back-to-top button in footer and added corresponding test
- modified outline surrounding cards on focus for keyboard navigation
- updated analytics for footer email signup
> Bugfixes: safari print, focus rings and analytics

- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/app-module/app-module-legacy.scss
Closes #3702 
- the height applied to pronunciation was causing overflow issues; removed explicit height
- applied similar padding to term to audio icon
**Bug:**
set viewport such that the term pronunciation wraps to 3 lines
https://www-test-acsf.cancer.gov/publications/dictionaries/cancer-terms/def/atypical-glandular-cells-of-undetermined-significance
**Expected result of fix:**
term wrapping to three lines no longer overflows the container
> (#3702) (Bugfix) pronunciation block wrapping fix

- composer.json
- composer.lock
- docker/web/Dockerfile
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/clamav.settings.yml
- Add clam AV to dockerfile
- Install and enable ClamAV drupal module
- Configure ClamAV module to point to executable
- Set outage action to allow
- Removed clamav settings from features yml file
Closes https://github.com/NCIOCPL/cgov-digital-platform/issues/3398
See https://github.com/NCIOCPL/cgov-digital-platform/pull/3476 for previous notes
> (#3398) Enable virus scanning for uploads

- .github/workflows/ci.yml
- acquia-pipelines.yml
- composer.json
- composer.lock
- docker/README.md
- docker/docker-compose.yml
- docker/web/Dockerfile
- docker/web/build/php-conf/json.ini
- docker/web/runtime/php_apache2.ini
- docker/web/runtime/php_cli.ini
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/007_file.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/016_biography-jen.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/016_biography-no-date.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/020_infographic_NCI_at_a_glance.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/020_infographic_cancer_and_the_human_tumor_atlas_network.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/020_infographic_pediatric_match.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/020_infographic_screen_to_save.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/021_infographic_pediatric_nci.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/200_blog-series.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/202_blog-post-cc.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/202_blog-post-ras.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/203_blog-post-pagingation.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/204_blog_post_hpv_vaccine.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/205_blog_post_vitamin_d.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/206_blog_post_NCI_director_d.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/300_press_release.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/biography-jennifer-loukissas.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/biography-stephen-chanock.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/src/Service/CgovYamlContentEventSubscriber.php
- phpunit.xml
- Updates Acquia Pipelines
- Updates Docker
- Removes json PHP module which is now core
- Updated php-dom-wrapper to work with PHP 8.0
- Fixed an error in our YAML Content subscriber that was incorrectly trying to access a key of an array without checking first.
- Update press release content to add values key to object that is required to be there. The underlying module code expects the key to be there. This was most likely just quietly not working before.
- Bad YAML content failed to set field_search_engine_restrictions correctly. It is unknown why cgov_metatag.module worked with the 0 value with PHP 7 vs PHP 8 failing. This would most likely be something with the Field loading or entity interface that is behaving differently with PHP 8.
- Updates phpunit.xml schema
> (#3266) Upgrade to PHP 8.0

- docroot/profiles/custom/cgov_site/translations/cgov_site.es.po
- We updated Drupal translations and this causes issues for our
translations being overwritten unless we have a newer file.
> (#3768) Add translation to workaround issue

- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/ncids_home_landing_macros.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-external--link-button-cta.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-external--link-button-guide-card.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-external--link-button-hero.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-internal--link-button-cta.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-internal--link-button-guide-card.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-internal--link-button-hero.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-promo-block-external.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-promo-block-internal.html.twig
ODE: https://ncigovcdode580.prod.acquia-sites.com/
Closes #3911
- This commit also fixes empty aria-label from being rendered out in the NCIDS Link Buttons and NCIDS Promo Block
> (#3911) Create macro for r2.1 components

- docker/web/Dockerfile
- docker/web/build/etc/apt/preferences.d/phd-chromium-browser
- Also removed ClamAV
- Had to mess around with how chromium-browser is installed.
Closes #3926
> (#3926) Bump Docker image to Ubuntu 20.04

- composer.lock
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/src/CgovHomeLandingPageTwigExtension.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_image/src/CgovImageTwigExtensions.php
- phpcs.xml
- phpstan.neon
ODE: [ncigovcdode615.prod.acquia-sites.com](http://ncigovcdode615.prod.acquia-sites.com/AH_VIEW)
Closes #4002
Closes #3843 
-------------
There is no logic change in this item. Everything is expected to work the same way, and ALL of this stuff is used in the templates that show the front-end HTML. So no backend was touched at all.
* Viewing NCIDS Home and Landing
* This is all front-end, no backend changes
* Specifically the code where we check what the Page Style is to draw different things.
* Also nothing really changed in the code, so if the old and new homepages display correctly in visual regressions, then it works.
* Updated how we get placeholder images for the new NCIDS home and landing.
* This is all front-end, no backend changes.
* The visual regression tests should check this. …
> (#4002) phpstan quick fixes for twig extension files

- .github/workflows/ci.yml
- .github/workflows/test-deployability.yml
- blt/blt.yml
- composer.json
- composer.lock
- docker/README.md
- docker/docker-compose.yml
- docker/web/Dockerfile
- docker/web/build/php-conf/opcache.ini
- docker/web/build/php-conf/xdebug.ini
- docker/web/runtime/php_apache2.ini
- docker/web/runtime/php_cli.ini
- docroot/modules/custom/app_module/tests/src/Functional/AppModuleEntityTest.php
- docroot/modules/custom/app_module/tests/src/Functional/AppModuleFieldBrowserTestBase.php
- docroot/modules/custom/app_module/tests/src/Functional/AppModulePluginBaseTest.php
- docroot/modules/custom/app_module/tests/src/Functional/AppModuleRenderArrayBuilderTest.php
- docroot/modules/custom/app_module/tests/src/Kernel/AppPathStorageTest.php
- docroot/modules/custom/app_module/tests/src/Kernel/AppPathTest.php
- docroot/modules/custom/cgov_adobe/tests/src/Functional/CgovAdobeRenderTest.php
- docroot/modules/custom/cgov_cts/tests/src/Functional/ZipCodeLookupResourceTest.php
- docroot/modules/custom/cgov_js_app_module/tests/src/Functional/JSOnlyAppModulePluginBuildTest.php
- docroot/modules/custom/json_data_field/tests/src/Functional/JsonDataFieldBrowserTestBase.php
- docroot/modules/custom/json_data_field/tests/src/Functional/JsonDataFieldWidgetTest.php
- docroot/modules/custom/json_data_field/tests/src/Kernel/KernelTestBase.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/CgovNavigationManager.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
- phpunit.xml
- Classy theme is going away in 10.0.0, and we needed to change out our tests that used it. They were mostly under docroot/modules.
- Bumped redirect module as it was throwing some errors
- Fixed deprecation warnings when strtolower(NULL) was *possible*. A number of changes will go into affect as part of PHP 9.0 resulting in value functions and other things dealing with values not working with NULL. The key term is NULL Coercion Consistency.  See https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg
Closes #3532
ODE: https://www-test-ac.cancer.gov
Regression Tests (Front-end and CMS): https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/actions/runs/6090063138/job/16524161910
> (#3532) Upgrade to PHP 8.1

- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/settings/ctsEnglishSettings.js
Change path list for CTS chat prompt on English pages to reflect paths
for both before and after moving the app modules.
Closes #4044
> (#4044) CTS pop-up paths

- cgov-drupal-users.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/cgov_saml_auth_config.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/cgov_saml_auth_config.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/tests/src/Functional/CgovSamlAuthConfigTest.php
- docroot/sites/settings/cgov_saml_auth_config.settings.php
- drush/Commands/cgov/CgovUserCommands.php
- Adds new user accounts to authmap table
- One time update to all users to ensure they are in authmap
- Unblocks user accounts on copy-down
Closes #4131
Closes #4129
> (#4131) Enforce SAML authentication

- docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/pathauto.pattern.application_page_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/pathauto.pattern.article_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/cgov_biography.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/pathauto.pattern.biography_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/pathauto.pattern.blog_series_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/pathauto.pattern.cgov_blog_post_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/pathauto.pattern.cancer_center_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/pathauto.pattern.cancer_research_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/pathauto.pattern.cthp_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/pathauto.pattern.event_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/pathauto.pattern.home_and_landing_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/pathauto.pattern.mini_landing_page_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/cgov_press_release.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/pathauto.pattern.press_release_url_pattern.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/src/Service/CgovYamlContentEventSubscriber.php
- docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/pathauto.pattern.pdq_cis_url.yml
- docroot/profiles/custom/cgov_site/modules/custom/pdq_core/pdq_core.install
- docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/pathauto.pattern.pdq_dis_url.yml
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block/breadcrumb/block--cgov-breadcrumb.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--cgov-breadcrumb.html.twig
ODE: https://ncigovcdode657.prod.acquia-sites.com/
This closes multiple D10 blockers.
* This updates the configurations that generate URLs
* So create a new page of each content type from the content menu. (Media are not affected)
* Also how the Contact Info blocks are created for Biographies and Press Releases.
* On a new ODE the contact blocks should show correctly.
* There is also an update hook to modify any content blocks that were created in the old way.
* This really can only be tested in ACSF, and it would only affect any site created after the 9.3 upgrade, so maybe nationalcancerplan.cancer.gov?
Closes #4163
This touched the breadcrumbs, and specifically any "crumbs" that do not have an href should not display a broken link. I *think* the best way is to visit `/api-test/b/1/1` …
> (#4163, #4165, #4166, #4167, #4164, #4168) Misc D10 Blockers

- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_article/src/CgovArticleTwigExtensions.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/015_article_cancer_genomics_research.content.yml
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/field--field-article-body.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/paragraph--body-section.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/article/field--field-article-body.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/article/paragraph--body-section.html.twig
- created new twig filter for formatting letters with accents and html entities.
- new twig filter applied on ncids_trans & cgov_common templates files which are related to body section in article content type.
- updated content yml for automated testing.
ODE- https://ncigovcdode674.prod.acquia-sites.com/
Closes #2343
> (#2343) Automated OTP Section Headings

- blt/src/Blt/Plugin/Commands/CgovAcsfCommands.php
- blt/src/Blt/Plugin/Commands/UsersCommands.php
- cgov-drupal-users.yml
- drush/Commands/cgov/CgovUserCommands.php
- block the admin user using key in loadUsers function.
- updated the post-install hook as we are handling block-admin in loadUsers function.
Closes #4211
> (#4211) Enabler: Block Admin in cgov:user:load-all

- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/chart.scss
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/index.js
* Added styling to remove extraneous bullet left on from legacy styling
Closes #3997
> (#3997) Extraneous bullet appears next to High Chart graphs

- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/CmsProtectionSubscriber.php
- docroot/sites/settings/cgov_caching.settings.php
I enabled CSS aggregation on all environments. The local.settings.php that ships with Drupal disables it, and that is ok. A dev can enable if they need local troubleshooting. However, if www-dev-ac was also www-cms-dev-ac or something and did not turn off aggregation, we would have encountered this issue MUCH sooner. 
Also locally once aggregation was enabled, it was pretty quick to test www-cms.devbox and verify the routes selected were correct. (Because it was reproducible easily with a `drush cr` and refresh the login page)
Closes #4305
> (#4305) Unblock css and js assets from login protection

- docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/imageCarousel/jquery.ui.imagecarousel.js
Closes #3856 .
Added aria label to next/prev buttons for image carousel.  
Confirmed that labels are in place for yt-video carousels as well.
> (#3856) image carousel next/prev label fix

- blt/src/Blt/Plugin/Commands/TranslateCommands.php
Translations are only re-imported if they change. If the core Drupal translations change but ours don't, then the core translations overwrite our month names. This forces a re-import of our translations every time we deploy.
Closes #3054
This PR should change nothing about the site. It only fixes an intermittent bug (that is never seen on lower tiers?).
> (#3054) Force re-import of cgov translations

- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing.field_landing_contents.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_flag_card_group.field_row_cards_unlimited.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_imageless_card_group.field_row_cards_unlimited.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_mlp_two_column_layout.field_left_content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_mlp_two_column_layout.field_right_content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_wide_guide_card.field_three_link_buttons.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/paragraphs.paragraphs_type.ncids_page_title_block.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids-mini-landing-example-page-ai.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids-mini-landing-example-page-ras.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids-mini-landing-example-page.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids_understanding_cancer.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids-mini-landing-2-column.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids-mini-landing-flag-card.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids_mini_landing_imageless_cards.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids_wide_guide_card.content.yml
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/node--cgov-mini-landing--ncids-default--full.html.twig
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/paragraph--ncids-page-title-block.html.twig
> (#4471) Remove MLP Title Paragraph and add it to MLP Template

- docroot/modules/custom/app_module/app_module.module
- docroot/modules/custom/app_module/app_module.services.yml
- docroot/modules/custom/app_module/src/AppModuleRenderArrayBuilder.php
- docroot/modules/custom/app_module/src/AppPathManager.php
- docroot/modules/custom/app_module/src/AppPathManagerInterface.php
- docroot/modules/custom/app_module/src/EventSubscriber/AppModuleRouteNormalizerBlockRequestSubscriber.php
- docroot/modules/custom/app_module/src/PathProcessor/PathProcessorAppModule.php
- docroot/modules/custom/app_module/tests/src/Functional/AppModuleRenderArrayBuilderTest.php
- docroot/modules/custom/app_module/tests/src/Unit/PathProcessorAppModuleTest.php
- docroot/modules/custom/cgov_js_app_module/cgov_js_app_module.module
- docroot/modules/custom/cgov_js_app_module/src/Plugin/app_module/JsOnlyAppModulePlugin.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.module
- Change how the JS only css is attached to a page to support D10.3.
- Switched from using $request->query to using $request->attributes. Attributes is meant for adding random things to. Query is actually the query params and acts funky if something is not cleaning up links. (Especial for the app module data when it gets serialized into a query param.)
- Fixed up the App Module's path processor to reduce lookups and get rid of some funkiness when it is called multiple times for app modules. processIncoming actually gets called for many outgoing urls. (It fires off a lot for a single request)
- CSS links seem to update correctly when an application page's css URL is updated. This previously needed a Drupal/ACSF cache clear for CSS changes to take effect.
- Implemented #2937 because moving …
> (#4530,#2937) Fix JS App Modules for D10.3

- docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.module
Closes #4568
I turned on caching locally and I was able to see the issue with `/news-events/cancer-currents-blog?page=1&topic=fda-approvals&topic=` poisoning the cache. Adding cache contexts for the 4(?) query parameter in use seems to remove the issue. I requested the bad url, the main page, each of the categories, and on first request breakpoints were hit in the pre hook. Once each loaded, subsequent visits did trip the breakpoint. So additional hits do not occur, nor does the cache get poisoned. 
The some other questions are:
*  we only started seeing issues in Dec,how was this working before, luck? 
* Do I need to add the page number to the context, or is the view generating and listening for that parameter enough?
* `$series` seems to always be null. Why is it there?
* Why does …
> (#4568) Fix blog cache issues

- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/article/article-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/biography/biography-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/blogs/blogs-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/cancer-center/cancer-center-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/cancer-research/cancer-research-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/event/event-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/infographic/infographic-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/mini-landing/mini-landing-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/press-release/press-release-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/video/video-legacy.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/legacy/transition-hacks/_inner-page-embed-image-hack.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-field-image-article/index.scss
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-image/index.scss
- Updates spacing below embedded images on mobile to be 24px (previously there was no space on mobile)
- Updates lead/embedded image captions to have consistent spacing between caption, credit, and enlarge button for both lead images as well as embedded images (previously there was bonus spacing below credits for embedded images)
- Closes #4731 
- Closes #4735
> R4 Common Features Feedback for Images (#4731, #4735)

- docroot/modules/custom/nci_definition/js/ckeditor5_plugins/glossifier/src/glossifyactioncommand.js
- docroot/modules/custom/nci_definition/js/ckeditor5_plugins/glossifier/src/glossifyediting.js
Biggest thing here is that for #4790 I had to change the return of html as a string instead of HTMLElement, which needed a number of unit test updates. In hindsight, maybe it was a hint that the expected output actually had an additional `<div>` wrapping the contents from the input. 😃 
Other than that, for #4788, the fix was an undocumented thing you need to do with inline widgets that someone else encountered in issue 17275 in https://github.com/ckeditor/ckeditor5/issues. Our fix is to just add the element name to the list of inline elements instead of needing a whole matcher. (`<nci-definition>` only has one use, and it is this, and the tag name is not shared with any other elements.)
Closes #4788 
Closes #4790
> (#4788, #4790) Glossifier Fixes

- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module.md
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Controller/CgovNavTreeController.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Form/CgovVocabManagerForm.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Manager/CgovVocabManager.php
- phpstan.neon
- CgovNaveTreeController.php
- Replace magic properties with get().
- CgovVocabManager.php
- Make parent_id nullable in getTaxonomyBreadcrumb(), to match caller.
- CgovVocabManagerForm.php
- Enable phpcs scanning.
- Populate docblock for getTreeArgs().
- buildForm(), define $complete_tree and do simple TRUE/FALSE vs. isset().
- Numerous formatting changes.
- CgovVocabManagerForm
- Reorder constructor parameters to put optional parameters at the end.
- buildForm(): make parameters explicitly nullable.
- @phpstan-ignore for properties added to TermInterface when objects are loaded.
- getParentNavInfo.php
- Retrieve fields via explicit get().
- Specify NULL return from getParentTerm() when no parent found.
- cgov_site_section.tokens.inc
- Initialize variable regardless of path.
- Replace …
> (#4761) phpstan fixes for taxonomy and site sections.

- composer.json
- composer.lock
- docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.cgov_dynamic_list.field_source_view.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.ncids_dynamic_list.field_source_view.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/251_events_landing.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/310_press_archive.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/311_news_events_landing.content.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids-mini-landing-dynamic-list-events.content.yml
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/listing/viewsreference--view-title.html.twig
Refactored YAML content files:
- 251_events_landing.content.yml
- 310_press_archive.content.yml
- 311_news_events_landing.content.yml
- 999_ncids-mini-landing-dynamic-list-events.content.yml
Closes #4941
Closes #1040
(So we need to bump and cleanup for #4941, but we are doing what is in #1040, so they should not be considered dupes.  So we finally are getting around to #1040 because we had to.)
> (#4941) update viewsreference.  Trim spaces in serialized landing page data.

- blt/blt.yml
- blt/src/Blt/Plugin/Commands/SlevenCommands.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovPurgeConfigInstaller.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_dummy_purger/cgov_dummy_purger.info.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_dummy_purger/cgov_dummy_purger.install
- docroot/profiles/custom/cgov_site/modules/custom/cgov_dummy_purger/cgov_dummy_purger.services.yml
- docroot/profiles/custom/cgov_site/modules/custom/cgov_dummy_purger/src/Plugin/Purge/Purger/CgovDummyPurger.php
- docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
Creates the dummy purger and install it on local development:
Closes #4758 
Now that local development supports purging we can clear the purge queue after content install:
Closes #3331 
The dummy purger will log out these purge requests on local development, so we don't need the log statement:
Closes #4958
> (#4758, #3331, #4958) Create dummy purger for local development
