README.md

Updated some folder structure notes

Testing Move

---

acquia-pipelines.yml
blt/blt.yml
docker/web/Dockerfile
docroot/profiles/custom/cgov_site/themes/custom/cgov/package-lock.json

- Setup initial pipelines file (based on PoC)
- Tweaked blt config to note cloud git repo
- Added command hooks for blt & cloud
Resolves #84

First crack at #43

---

acquia-pipelines.yml
docker/docker.env.sample
docker/web/Dockerfile
scripts/pipelines/build_artifact
scripts/pipelines/setup_app
scripts/pipelines/setup_env
scripts/pipelines/tests
scripts/pipelines/validate

- Sets up build scripts
- Updated Node to 10.x
- Create Simpletest DB
Also fixes #86

More Pipeline Changes for #43

---

docker/README.md

Add note with how to access the site after setup.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_date_display_mode.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_date_posted.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_date_reviewed.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_date_updated.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/FieldStorage/CGovFieldStorageTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/RolesTest.php

Add field storage for date_posted/reviewed/updated/display_mode and update tests

Fixes #110 - Add field storage for common date fields

---

docroot/profiles/custom/cgov_site/cgov_site.install
docroot/profiles/custom/cgov_site/cgov_site.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php

Move CgovSiteTools from profile to core

---

docroot/profiles/custom/cgov_site/cgov_site.install
docroot/profiles/custom/cgov_site/cgov_site.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/modules/cgov_article/config/install/field.field.node.cgov_article.body.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php

Fixing errant squash instead of merge.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php

Fixes the core tools conflicts

Resolve merge conflicts in CgovCoreTools

---

docroot/profiles/custom/cgov_site/config/install/block.block.cgov_common_languagebar.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/LanguageBar.php
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block/page_options/block--cgov-language-bar.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/layout/page.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/layout/regions/region--language-bar.html.twig

Add Language Bar

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/user.role.pdq_importer.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/workflows.workflow.pdq_workflow.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/WorkflowTest.php

Batteries (_i.e._ `phpunit` tests) included.

Implement Drupal workflow for PDQ content (fixes #257 and #258)

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/WorkflowTest.php

Let editors delete archived content (closes #385)

---

docroot/profiles/custom/cgov_site/cgov_site.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/core.date_format.cgov_display_date.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/language/core.date_format.cgov_display_date.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/node--cgov-article--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content_page_macros.twig
docroot/profiles/custom/cgov_site/translations/cgov_site.es.po

Partially takes care of #465
Only drawing selected dates is not working without additional functions

Added in date template

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_form_display.node.pdq_cancer_information_summary.default.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_view_display.node.pdq_cancer_information_summary.default.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_view_display.node.pdq_cancer_information_summary.teaser.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.field.node.pdq_cancer_information_summary.field_pdq_cdr_id.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.field.node.pdq_cancer_information_summary.field_pdq_summary_type.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.storage.node.field_pdq_summary_type.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.info.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/PDQSummaryTest.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/config/install/field.storage.node.field_pdq_cdr_id.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/tests/src/Kernel/FieldStorage/PDQFieldStorageTest.php

Create the Summary Type field for PDQ Summary (#404)
Create CDR ID field. (#403)

Pdq summary fields

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_syndicate.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_syndication_keywords.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/FieldStorage/CGovFieldStorageTest.php

Defines field_syndication (boolean) and field_syndication_keyword (text) fields.

Define syndication fields (#203)

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_form_display.node.pdq_cancer_information_summary.default.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/Plugin/rest/resource/PDQResource.php

Use paragraphs_classic_asymmetric widget

Use paragraphs_classic_asymmetric widget

---

composer.json
composer.lock

Updated BLT

---

blt/blt.yml
docker/docker.env.sample

Closes #239
Credit to Adrian for the original fix - I only changed the name

Updating machine name to prep for microsite instance

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/README.md
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.info.yml

Adds basic documentation for the pdq_cancer_information_summary module.

Basic module documentation for pdq_cancer_information_summary.

---

docroot/sites/default/settings/default.local.settings.php
phpcs.xml

Update ACSF Site Variable to match fix in BLT 9.2.3

---

docker/web/Dockerfile

Pegged npm to v6.5

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_form_display.node.cgov_article.default.yml

Changed Article's SER form widget to select.

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/field.field.node.pdq_cancer_information_summary.field_public_use.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/PDQSummaryTest.php

This accomodates the change from #503.

Update public_use field to be a dropdown.

---

blt/src/Commands/UsersCommand.php
drush/Commands/cgov/CgovUserCommands.php

This will prevent the password from appearing on the command line,
additionally, this also means we don't have to worry about characters
being interpreted as variables.

Updated admin user command to use file.

---

docroot/profiles/custom/cgov_site/cgov_site.info.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/README.md
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/PDQCancerSummaryTest.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/config/install/field.storage.node.field_pdq_audio_id.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/config/install/field.storage.node.field_pdq_pronunciation_key.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/README.md
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.base_field_override.node.pdq_drug_information_summary.promote.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.base_field_override.node.pdq_drug_information_summary.status.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.entity_form_display.node.pdq_drug_information_summary.default.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.entity_view_display.node.pdq_drug_information_summary.default.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.entity_view_display.node.pdq_drug_information_summary.teaser.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.body.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_date_posted.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_date_updated.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_page_description.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_pdq_audio_id.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_pdq_cdr_id.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_pdq_pronunciation_key.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_public_use.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/language.content_settings.node.pdq_drug_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/node.type.pdq_drug_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/pdq_drug_information_summary.info.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/pdq_drug_information_summary.install
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/pdq_drug_information_summary.module
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/tests/src/Functional/PDQDrugSummaryTest.php

Define PDQ Drug Information Summary

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.base_field_override.node.cgov_mini_landing_page.promote.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.base_field_override.node.cgov_mini_landing_page.status.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.base_field_override.node.cgov_mini_landing_page.title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.node.cgov_mini_landing_page.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_mini_landing_page.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_mini_landing_page.feature_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_mini_landing_page.feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_mini_landing_page.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_mini_landing_page.teaser.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_mini_landing_page.thumbnail_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_mini_landing_page.thumbnail_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_browser_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_card_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_date_display_mode.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_date_posted.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_date_reviewed.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_date_updated.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_feature_card_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_image_promotional.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_landing_contents.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_list_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_page_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_pretty_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_search_engine_restrictions.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_short_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing_page.field_site_section.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/language.content_settings.node.cgov_mini_landing_page.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/node.type.cgov_mini_landing_page.yml

Added Mini Landing

---

docroot/profiles/custom/cgov_site/cgov_site.info.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/PDQCancerSummaryTest.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/config/install/field.storage.node.field_pdq_audio_id.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/config/install/field.storage.node.field_pdq_pronunciation_key.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/README.md
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.base_field_override.node.pdq_drug_information_summary.promote.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.base_field_override.node.pdq_drug_information_summary.status.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.entity_form_display.node.pdq_drug_information_summary.default.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.entity_view_display.node.pdq_drug_information_summary.default.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.entity_view_display.node.pdq_drug_information_summary.teaser.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.body.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_date_posted.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_date_updated.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_page_description.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_pdq_audio_id.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_pdq_cdr_id.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_pdq_pronunciation_key.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/field.field.node.pdq_drug_information_summary.field_public_use.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/language.content_settings.node.pdq_drug_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/node.type.pdq_drug_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/pdq_drug_information_summary.info.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/pdq_drug_information_summary.install
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/pdq_drug_information_summary.module
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/tests/src/Functional/PDQDrugSummaryTest.php

Define PDQ Drug Information Summary (#634)

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc

* Modify custom token hook to add computed_path

Add token changes for site section.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/core.entity_form_display.taxonomy_term.cgov_site_sections.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Plugin/Validation/Constraint/UniqueCgovUrlConstraintValidator.php

* Modifying the return value to a bool and casting the potentially null ID to 0

Fix for validation casting error. Update form display.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_view_display.node.cgov_cancer_center.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.media.cgov_image.image_crop_article.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_mode.media.image_crop_article.yml

* Closes #702
* Closes #701
* Also updated Cancer Centers full display to use Article image crop

Added Article image crop and formatted Dates/Images on Cancer Center.

---

composer.json
composer.lock

* Updates acquia_connector package
* Adds search_api and solarium packages
* Closes 718

Update acquia_connector package so tests don't fail anymore

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/src/Service/CgovYamlContentEventSubscriber.php

Closes #717.
This adds support for programmatically associating nodes without pretty urls with site sections landing page entity reference field.
In short: An entity is saved. If that entity is a node and has the requisite fields and does not have a pretty url and does have an associated site section, in theory it should be a landing page. We can retrieve that referenced site section and add a circular reference to the current entity in it's landing page field. Completing the loop of setting up a navigation structure on install.

Add in support for automatically setting site section landing pages

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/press_release.content.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/press_release/node--cgov-press-release--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/layout/regions/region.html.twig

Updating template for Press Releases.
Adding `field_press_release_type` to yaml content.
Resetting region template so extraneous elements are removed from html which were breaking CSS selectors.
No library needed.

Ticket/607 Press Release Styles

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_form_display.node.cgov_cancer_center.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_view_display.node.cgov_cancer_center.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_view_display.node.cgov_cancer_center.feature_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_view_display.node.cgov_cancer_center.feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_view_display.node.cgov_cancer_center.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_view_display.node.cgov_cancer_center.teaser.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_view_display.node.cgov_cancer_center.thumbnail_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_view_display.node.cgov_cancer_center.thumbnail_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/field.field.node.cgov_cancer_center.field_pretty_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/field.field.node.cgov_cancer_center.field_site_section.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/pathauto.pattern.cancer_center_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/cancer_center-dana-farber-harvard-cc.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/cancer_center-duke-cc.content.yml

Cancer center field updates: Pretty URL, Site Section

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/field.field.node.cgov_article.field_pretty_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog_post/config/install/field.field.node.cgov_blog_post.field_pretty_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_pretty_url.yml

Update helper text for Pretty Url common field.

---

cgov-drupal-users.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/user.role.content_author.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/user.role.image_manager.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/cgov_media.install

* Fixed an issue where authors could not select images nor content using entity browser
* Updated Pre-populated users to reflect image_manager role.
Closes #455

Added Image Manager Role/Permissions

---

cgov-drupal-users.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/user.role.content_author.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/user.role.image_manager.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/cgov_media.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/cgov_yaml_content.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/090_research_key-initiatives.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/press_release.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/src/Service/CgovYamlContentEventSubscriber.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.module
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/Plugin/rest/resource/PDQResource.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/ApiTest.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/Plugin/rest/resource/PDQResource.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/src/Plugin/rest/resource/PDQResource.php

Merge latest develop into "feature/cgov-blog-series"

Merge latest develop into "feature/cgov-blog-series"

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/cgov_site.info.yml
docroot/profiles/custom/cgov_site/config/install/disqus.settings.yml
docroot/profiles/custom/cgov_site/config/install/user.role.administrator.yml
docroot/profiles/custom/cgov_site/config/install/user.role.authenticated.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog_post/cgov_blog_post.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog_post/config/install/core.entity_form_display.node.cgov_blog_post.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog_post/config/install/core.entity_view_display.node.cgov_blog_post.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog_post/config/install/core.entity_view_display.node.cgov_blog_post.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog_post/config/install/field.field.node.cgov_blog_post.field_blog_comments.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog_post/config/install/field.storage.node.field_blog_comments.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/user.role.site_admin.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog_post/node--cgov-blog-post--full.html.twig

Merge "ticket/357-blog-comments" into "feature/disqus"

Merge "ticket/357-blog-comments" into "feature/disqus"

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_dis.content.yml

Create sample PDQ DIS YAML (#656)

---

simplesamlphp/config/acquia_config.php

Reinstate use of secrets file.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/cgov_biography.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_campus.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/language.content_settings.taxonomy_term.cgov_biography_campuses.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/taxonomy.vocabulary.cgov_biography_campuses.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/cgov_cancer_center.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/field.field.node.cgov_cancer_center.field_institution_type.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/language.content_settings.taxonomy_term.cgov_cancer_center_types.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/taxonomy.vocabulary.cgov_cancer_center_types.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/biography-jennifer-loukissas.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/biography-stephen-chanock.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/cancer_center-dana-farber-harvard-cc.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/cancer_center-duke-cc.content.yml

Update singular taxonomy names to pural

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/cgov_site.info.yml

There are a number of tickets that require this module. Adding it into the core now so as to reduce composer conflicts while each PR that uses it is waiting review.

Added Entity Embed

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme

Preview link doesn't work for Content in Editing (in moderated view)

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/layout/html.html.twig

Fixes #504 
TESTING: On http://ncigovcdode62.prod.acquia-sites.com/

#504 Add favicon (and mobile app icons)

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/homelanding/Homelanding.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/image/media--cgov-image.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/list_item_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/node--thumbnail-card-image.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_managed-lists.scss

1. list item title is now displayed as a 20px h3 (from 16px)
2. fixed thumbnail size to be larger on secondary pages (25% width and no left padding)
3. fixed hover over image changing title color
4. reduced font size for compact list items to 18px from 20px

Bugfix #1147 - List display discrepancies

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_form_display.paragraph.body_section.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/field.field.paragraph.body_section.field_body_section_heading.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/field.storage.paragraph.field_body_section_heading.yml

Closes #621 
Updates Article body_section_heading paragraph field to text_long/WYSIWYG.

Update body_section_heading paragraph field to text_long/WYSIWYG.

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/cgov_site.info.yml
docroot/profiles/custom/cgov_site/config/install/editor.editor.full_html.yml
docroot/profiles/custom/cgov_site/config/install/editor.editor.streamlined.yml
docroot/profiles/custom/cgov_site/config/install/filter.format.full_html.yml
docroot/profiles/custom/cgov_site/config/install/filter.format.streamlined.yml
docroot/profiles/custom/cgov_site/config/install/linkit.linkit_profile.cgov_inline_links.yml
docroot/profiles/custom/cgov_site/config/install/user.role.admin_ui.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/user.role.image_manager.yml

This adds inline linking to all node content, and videos. This will allow a user to find the page they want to link to via its URL or title.
This closes #1165. 
ODE: ncigovcdode67.prod.acquia-sites.com

Added Inline Linking using Linkit

---

docroot/profiles/custom/cgov_site/config/install/views.view.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/entity_browser.browser.cgov_content_browser.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/views.view.cgov_content_browser.yml

ODE: ncigovcdode68.prod.acquia-sites.com

Implement Content Browsing Experience

---

blt/blt.yml
hooks/common/post-code-deploy/post-code-deploy.sh

Int is not part of a "dev" tier. There are no tiers, just environments.

Treat "int" as its own entity.

---

docroot/profiles/custom/cgov_site/config/install/views.view.media.yml
docroot/profiles/custom/cgov_site/config/install/views.view.moderated_content.yml

Move operations to left on Moderation View

---

docroot/profiles/custom/cgov_site/config/install/views.view.media.yml
docroot/profiles/custom/cgov_site/config/install/views.view.moderated_content.yml

Move operations to left on Moderation View (#1204)

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php

(closes #1186)
* Filter categories by owner series.

Filtered categories

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/homelanding/Homelanding.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/homelanding/Homelanding.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/press_release/views-view--press-releases--pr-home-block.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/list_item_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/paragraph--cgov-dynamic-list.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/paragraph--cgov-list.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_managed-lists.scss

- thumbnail list hovers are now independent, no dirty js
- dynamic lists given some styling traits of managed lists
- small styling tweaks to match prod

More list styling

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/press_release/node--press-view-archive-item.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/press_release/node--press-view-home-list-item.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/field--paragraph--field-list-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/paragraph--cgov-external-link--list-item-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/paragraph--cgov-internal-link--list-item-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_managed-lists.scss

- spacing of list title fixed by placing label in a row
- all lists, except for compact list items, should have the title as an h3, all the same size(20px)
- Includes fix for bug #1235 : Internal compact list links should display short title instead of title

List CRs and bug fixes

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/homelanding/Homelanding.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/field--paragraph--field-list-title.html.twig

List titles should by default be left aligned to the left edge of the list.  Container should handle positioning if varied from that.

Lists: title alignment

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/pathauto.pattern.cgov_blog_topics.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogArchive.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogCategories.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc

* Added token and logic for Blog Topics pages 
* Cleaned up plugin manager functions w/null checks

Ticket/categories (#54)

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/cgov_event.routing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_site_section.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/event/node--cgov-event--full.html.twig

* Adds "Add to Outlook Calendar" function to events (Closes #985)
* Add ical dependency
* Add controller to create ical file for cgov_event node
* Add route for ical file download for cgov_event node
* Add link to Add to outlook calendar to template
* Bug fixes:
* Display year on start and end dates if spans across two years (Closes #1059)
* Rearrage display order to Venue, Room, City/State (Closes #1096)

Add to Outlook Calendar link (#1188)

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/cthp/CTHP.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cthp/node--cgov-cthp--full.html.twig
docroot/profiles/custom/cgov_site/translations/cgov_site.es.po

Made the toggle text translatable, putting them in trans tags

Translatable toggle text

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/README.md

Rebuild after update from `develop`.

Single signon

---

docs/testing/behat.md
tests/behat/behat.yml
tests/behat/example.local.yml
tests/behat/features/ContentWorkflow.feature
tests/behat/features/PDQ.feature
tests/behat/features/Translation.feature
tests/behat/features/bootstrap/Drupal/FeatureContext.php

This PR sets up basic Behat test examples/scenarios for the project. 
1. Updates Behat settings/configuration.
2. Adds Initial Documentation on Behat Testing
3. Stubs out some initial steps/scenarios for feedback
`blt tests:behat`
1. Behats default timeout is 5 seconds. On both local and pipelines environments, this is too low and many steps will timeout and randomly fail. Setting this to 10 seconds seems to be enough to avoid these issues.
2. Updated behat.yml to only run scenarios tagged with @smoke and ignore scenarios tagged with @todo when a user runs `blt tests:behat`
3. Entered some basic feature context scenarios for switching in and out of iframes.

NCI-000: Initial setup of Behat tests.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/010_article_sexual_health_issues_men_placeholder.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/010_article_sexual_health_issues_women_placeholder.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/010_coping_feelings_stress_fs.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/011_article_coping_self_image.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/011_coping_feelings.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/012_article-psychological-stress-and-cancer.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/014_article_vitamin_d_placeholder.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/015_article_cancer_genomics_research.content.yml

There were a number of malformed YAML files pulled into develop as part of PR #1190. This causes builds to fail, and is currently breaking dev server, and anything that gets refreshed with develop.

Fixes a number of content issues causing builds to fail

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.paragraph.cgov_card_raw_html.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.paragraph.cgov_card_raw_html.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_landing_contents.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing.field_landing_contents.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.cgov_card_raw_html.field_raw_html.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_raw_html.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/paragraphs.paragraphs_type.cgov_two_item_feature_row.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/010_key_initiatives_ras_central.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/099_about-cancer.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/099_grants_training.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/099_research.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/099_types.content.yml

* Add card_raw_html to Home/Landing Contents Field #1343
* Raw HTML Block Card should have Raw HTML Field #1169
* Typo - Add two Item Feature Card Row on Mini Landing Page #847

Some migration enhancements/fixes for Landing Pages

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/cthp/CTHP.scss

Ticket #1346 : Fix styling for external(non cancer.gov) links in CTHP dropdown at desktop sizes

CTHP dropdown external links

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cthp/paragraph--cgov-cthp-video-card.html.twig

Display video feature card desc if no target URL

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_browser_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_card_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_event_series.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_feature_card_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_image_article.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_image_promotional.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_list_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_page_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_pretty_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_search_engine_restrictions.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_short_title.yml

Event tooltip and form updates

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_form_display.paragraph.cgov_external_link.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_form_display.paragraph.cgov_internal_link.default.yml

Update form display for internal/external links

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/Breadcrumb.php

Closes #1377.
ODE: http://ncigovcdode95.prod.acquia-sites.com

Ticket #1377 - Constrain breadcrumbs to above curr landing page

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_image/tests/src/Kernel/CgovImageFieldStorageTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/cgov_media.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_browser_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_date_posted.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_feature_card_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_list_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_related_resources.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_short_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/tests/src/Kernel/CgovMediaFieldStorageTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_form_display.media.cgov_video.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_browser_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_card_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_date_display_mode.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_date_posted.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_date_reviewed.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_feature_card_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_list_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_meta_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_pretty_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_related_resources.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_search_engine_restrictions.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_short_title.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/video/media--cgov-video--full.html.twig

Closes #1314 
* Adds Related Resources, Meta Description, and S.E Restriction fields
* Update Field Order / Tooltips
* Limit text formats for WYSIWYG 
* Fix date display bug

Ticket/1314 Video Form Updates and Date Display Bug

---

docroot/profiles/custom/cgov_site/config/install/editor.editor.full_html.yml
docroot/profiles/custom/cgov_site/config/install/editor.editor.streamlined.yml
docroot/profiles/custom/cgov_site/config/install/filter.format.streamlined.yml
docroot/profiles/custom/cgov_site/config/install/linkit.linkit_profile.cgov_inline_links.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.cgov_list.field_list_items.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/paragraphs.paragraphs_type.cgov_card_external.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/paragraphs.paragraphs_type.cgov_card_internal.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/field--field-article-body.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/node--cgov-article--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/paragraph--body-section.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/node--cgov-blog-post--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/event/node--cgov-event--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/press_release/node--cgov-press-release--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/field/field--field-image-article.html.twig

Closes #1421 , closes #1474, closes #1481, closes #1476 , closes #1478 , closes #1382 
ODE: http://ncigovcdode91.prod.acquia-sites.com/

#1421, #1474, #1481, #1476, #1478, #1382 - Configuration changes to admin UI

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module

Default admin UI pages to English.

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/cgov_site.info.yml
docroot/profiles/custom/cgov_site/config/install/redirect.settings.yml

Closes #1525 
Added in redirect module which handles support for route -> alias redirects. I did turn off auto redirect generation, that was bound to get out of hand. This could support redirections, but will it scale? For now, this is just satisfying #1525.

(#1525) 301 redirect route to aliases.

---

docroot/profiles/custom/cgov_site/config/install/pathauto.settings.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module

Closes #1304 
Closes #1582
Allows periods in pretty URL fields.
ODE: ncigovcdode115.prod.acquia-sites.com

Allow periods for Pretty URLs.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/cgov_media.links.task.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/cgov_media.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/views.view.moderated_media.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/workflows.workflow.image_workflow.yml

closes #1206
ODE: http://ncigovcdode110.prod.acquia-sites.com

(#1206) Add moderated media tab to content page

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/Plugin/rest/resource/PDQResource.php

Closes #1610 
An easy one for you (I think), @bryanpizzillo.

(#1610) Report success for removal of missing PDQ items

---

blt/blt.yml
composer.json
composer.lock
docroot/.htaccess
docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/README.md
docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/cgov_saml_auth_config.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/cgov_saml_auth_config.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/config/install/cgov_saml_auth_config.settings.yml
docroot/simplesaml
drush/Commands/cgov/CgovUserCommands.php
patches/htaccess-saml.patch
phpcs.xml
simplesamlphp/config/acquia_config.php
simplesamlphp/config/authsources.php
simplesamlphp/config/config.php
simplesamlphp/metadata/saml20-idp-remote.php

Configure to use NIH Authentication

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_file/cgov_file.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_file/cgov_file.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_file/config/install/field.field.media.cgov_file.field_media_file.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_file/src/EventSubscriber/DirectFileDownloadSubscriber.php

This will be on http://ncigovcdode125.prod.acquia-sites.com/ whenever the build finishes and I deploy it there.
Closes #1166 
Closes #1521

File Enhancements (Direct Downloads and All File Extensions)

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/field.field.node.cgov_press_release.field_date_display_mode.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/node--cgov-biography--full.html.twig

* Closes #1583 
* Closes #1546

(#1583, #1546) Biography Title in Template & Press Release Date Display Mode Tooltip (bug fixes)

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/crop.type.16x9.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/crop.type.3x4.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/crop.type.4x3.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/crop.type.9x16.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/crop.type.thumbnail.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/image.style.cgov_featured.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/image.style.cgov_panoramic.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/image.style.cgov_thumbnail.yml

(#1396) Image Styles have incorrect scaling

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/CgovNavigationManager.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/src/EventSubscriber/ImageEventSubscriber.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/src/Plugin/PathProcessor/ImageRedirectProcessor.php

Closes #1668, closes #1657.
ODE: http://ncigovcdode133.prod.acquia-sites.com

(#1668, #1657) Makes Image media/{id} go directly to raw file and fix mobile nav language flag

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/core.entity_form_display.paragraph.cgov_cthp_feature_card_internal.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/core.entity_view_display.paragraph.cgov_cthp_feature_card_internal.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/field.field.paragraph.cgov_cthp_feature_card_internal.field_override_image_promotional.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cthp/paragraph--cgov-cthp-feature-card-internal.html.twig

* Add override image promotional field to CTHP Internal Feature Card
* Reorder fields on CTHP Internal Feature Card form
* Display override img promotional if set on CTHP Internal Feature Card
* Closes #1692

(#1692) Internal Feature Card CRs/bug fixes

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/field.field.node.cgov_blog_post.field_blog_series.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/field.field.node.cgov_blog_series.field_featured_posts.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/field.field.taxonomy_term.cgov_blog_topics.field_owner_blog.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/schema/cgov_core.schema.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/EntityReferenceSelection/CgovUnpublishedSelection.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/field.field.node.cgov_cthp.field_audience_toggle.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/field.field.paragraph.cgov_cthp_feature_card.field_cthp_featured_content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/field.field.paragraph.cgov_cthp_guide_card.field_cthp_pdq_links.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/field.field.paragraph.cgov_cthp_research_card.field_cthp_research_page.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/field.field.paragraph.cgov_cthp_video_card.field_cthp_video.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.cgov_multimedia_row.field_mm_media_item.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.cgov_dynamic_list.field_view_more_link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.cgov_internal_link.field_internal_link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.cgov_media_link.field_media_link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.cgov_card_internal.field_featured_item.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/field.field.taxonomy_term.cgov_site_sections.field_landing_page.yml

Closes #1231 
ODE: http://ncigovcdode138.prod.acquia-sites.com/

(#1231) Unpublished Related Internal Link Produces Error

---

docroot/profiles/custom/cgov_site/config/install/metatag.metatag_defaults.global.yml
docroot/profiles/custom/cgov_site/config/install/metatag.metatag_defaults.node.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/cgov_biography.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/core.entity_form_display.node.cgov_blog_series.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_post.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/cgov_cancer_center.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/cgov_cancer_research.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/cgov_cthp.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/metatag.metatag_defaults.node__cgov_cthp.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/cgov_event.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/cgov_infographic.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/cgov_press_release.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/core.entity_form_display.taxonomy_term.cgov_site_sections.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/core.entity_view_display.taxonomy_term.cgov_site_sections.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/field.field.taxonomy_term.cgov_site_sections.field_channel.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/field.field.taxonomy_term.cgov_site_sections.field_content_group.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/field.storage.taxonomy_term.field_channel.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/field.storage.taxonomy_term.field_content_group.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/cgov_video.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/200_blog-series.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/202_blog-post-cc.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/900_pet_nav.content.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.info.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/metatag.metatag_defaults.node__pdq_drug_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/pdq_drug_information_summary.info.yml

(#321, #1638) Merge "feature/dtm-analytics" into develop

---

composer.json
composer.lock

* Added ctools module patch for issue 2785499

(#1718) Error message on missing node path

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/SectionNav.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_all_day_event.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.cgov_card_external.field_featured_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.cgov_card_internal.field_featured_item.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/ckeditor/Ckeditor.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block/section_nav/block--cgov-section-nav.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/block--cgov-disqus.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/node--cgov-home-landing--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/press_release/node--cgov-press-release--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/layout/regions/region--section-nav.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/page/page--404-en.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/page/page--404-es.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_contact.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_errorPage.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_general.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_mainContent.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_nav.scss

ODE: http://ncigovcdode157.prod.acquia-sites.com

(#1704, #1701, #1687, #1637, #1702, #1729, #1757, #1505, #1742, #1762, #1771, #1766) Brendan Bug Fix Branch (and 404 pages)

---

FrontendGlobals.json
docroot/profiles/custom/cgov_site/config/install/cgov_core.frontend_globals.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/core.entity_form_display.node.cgov_blog_post.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.features.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.links.menu.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.permissions.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.routing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/schema/cgov_core.schema.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Form/FrontendGlobalsForm.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/PathProcessor/UrlProcessor.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/cgov_infographic.module
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/exitDisclaimer/exitDisclaimer.js
docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/templates/embeds/infographic/media--cgov-infographic--infographic-display-article-large.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/templates/embeds/infographic/media--cgov-infographic--infographic-display-article-medium.html.twig
docroot/profiles/custom/cgov_site/translations/cgov_site.es.po
hooks/common/post-code-deploy/post-code-deploy.sh
hooks/common/post-code-update/post-code-update.sh

Closes #1830 
Closes #1807 
Closes #1842
Closes #1854 
Closes #1855 
Closes #1666 
Closes #1737
ODE: http://ncigovcdode165.prod.acquia-sites.com/

(#1830, #1807, #1842, #1854, #1855, #1666, #1737) Brendan Mega PR

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/field.storage.taxonomy_term.field_navigation_label.yml

(#1896) Increase character limit for field_navigation_label

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_blogpost_en_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_blogpost_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_cancercenter_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_citation_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_contentblock_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_cthpcontentblock_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_event_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_infographic_en_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_infographic_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_paragraph_en_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_paragraph_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_pressrelease_en_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_pressrelease_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/GeneratePlaceholders.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/RemoveRxWrapper.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceEmbeds.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceLinks.php
scripts/utility/cgov_migration_load.sh

ODE:http://ncigovcdode173.prod.acquia-sites.com
Mangled Content / Missing Words 
http://ncigovcdode173.prod.acquia-sites.com/about-cancer/causes-prevention/risk/infectious-agents
Closes #1834   (Embed replacement)
Inline Feature Cards
http://ncigovcdode173.prod.acquia-sites.com/research/key-initiatives/immunotherapy
Closes #1795  (Link replacement)
Links to Nodes 
http://ncigovcdode173.prod.acquia-sites.com/about-cancer/coping/adjusting-to-cancer
Press Release Pipe Character / Link Replacement
http://ncigovcdode173.prod.acquia-sites.com/news-events/press-releases/2015

Inline Variant Processing / Bugfixes

---

composer.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/cgov_cthp.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/field.field.paragraph.cgov_cthp_feature_card_external.field_cthp_featured_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.media.cgov_contextual_image.image_display_inline.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.media.cgov_image.image_display_inline.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_mode.media.image_display_inline.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/embed.button.cgov_image_button.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/cgov_list.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.cgov_external_link.field_external_link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/cgov_migration.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/CgovPluginBase.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/cgov_promo.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.cgov_card_external.field_featured_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.cgov_card_external.field_override_card_title.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/image/entity-embed-container--media.image-display-inline.html.twig

Create an Embeddable Image Mode for Inline Images (Closes #1936)
Allow external links to have internal links. (Closes #1938)
ODE: ncigovcdode161.prod.acquia-sites.com

Inline images and Internal External Links

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/cgov_migration.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceLinks.php

Decode HTML entities for specific fields. Fix missing link text issue.

---

blt/blt.yml
docroot/profiles/custom/cgov_site/cgov_site.info.yml
hooks/common/post-code-deploy/post-code-deploy.sh
hooks/common/post-code-update/post-code-update.sh

- Add support for "ode" environment for toggle modules.

Remove cgov_caching_cdn from profile

---

acsf-convert/convert-ace-acsf.sh
acsf-convert/files/cgov-drupal-users.yml
acsf-convert/files/factory-hooks/db-update/z-cgov-post-update.sh
acsf-convert/files/factory-hooks/post-install/z-cgov-post-install.php
blt/src/Commands/CgovAcsfCommand.php
drush/Commands/cgov/CgovUserCommands.php

- Added blt command for post-install, db-update, post-staging-deploy.
- Added drush command to block admin user account.
- Made user's password optional for cgov:user:load-all
- Updated users loading for ACSF + ACSF users file
- Updated factory hooks for calling our BLT commands

ACSF Factory Hook Scripts

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/cgov_site.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/workflows.workflow.editorial_workflow.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.scss

Trying out the Moderation Sidebar module.
Closes #765 
ODE: http://ncigovcdode149.prod.acquia-sites.com/AH_VIEW

(#765) Improve the work process

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/CgovPluginBase.php

Closes #2020
2238 - infographic_display_article_large - center align
1833 - video_display_small_title  - right align

(2020) Fix for variant mapping issue with variants: 2238, 1833

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/CgovPluginBase.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceEmbeds.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceLinks.php

Closes #2008 
Cross-site link replacement on micro-sites.

(#2008) Links are not being switched over on microsites.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/cthp/CTHP.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/floatingDelighter/rules.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/page--cgov-blog-post.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/page--cgov-blog-series.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cthp/node--cthp-guide-card-list-item.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cthp/page--cgov-cthp.html.twig

ODE: http://ncigovcdode190.prod.acquia-sites.com

(#2005, #2004, #2018, #2006, #1993, #2017) Bugfixes

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/cgov_site.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_caching_cdn/cgov_caching_cdn.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_caching_cdn/cgov_caching_cdn.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_caching_cdn/config/install/config_perms.custom_perms_entity.akamai_purge_status.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/config_perms.custom_perms_entity.basic_site_settings.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/config_perms.custom_perms_entity.file_system.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/config_perms.custom_perms_entity.logging_and_errors.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/config_perms.custom_perms_entity.rss_publishing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/config_perms.custom_perms_entity.view_field_list.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/config_perms.custom_perms_entity.view_plugins.yml

Addresses:
(#1951) User in SiteAdmin role cannot assign roles. 
(#1986) Adjust permissions for SiteAdmin role.
Closes #1951
Closes #1986

Role roll up

---

docker/docker.env.sample
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/CmsProtectionSubscriber.php

- Added EventSubscriber for protecting site.
- Updated docker env sample to add www-cms for better
testing of protection subscriber.
This is mostly going to be a build for testing against ACSF

(#2014) Require logins for any *-cms website

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/homelanding/Homelanding.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/blue/entrypoints/Blue.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/green/entrypoints/Green.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/purple/entrypoints/Purple.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_embedded-entity.scss

Closes #1983 .
Closes #1984 .
Closes #1985 .
Knocking out microsite styling for microsite themes.
ODE: http://ncigovcdode189.prod.acquia-sites.com/

Microsite styling fixes

---

composer.json
composer.lock

(#2067) Enable Memcache on Cloud Environments.

---

composer.json
composer.lock

(#2071) Patch Purger for Drush Support

---

composer.json
composer.lock
drush/Commands/cgov/CgovUtilCommands.php
hooks/common/post-code-deploy/post-code-deploy.sh
hooks/common/post-code-update/post-code-update.sh

Try number 3 for getting re-installs working.

(#2067) Re-enabled Memcache

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/modal/_modal.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_footer.scss

Closes #1956 .
Closes #1917 .
Fix for icons by moving them into ::before pseudo-element.

Icon fixes

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogPager.php

* Added sort utility function for Blog Post pager link issues

(#2074) Blog Post pagination issue

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/field.field.node.cgov_blog_series.field_banner_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_file/config/install/field.field.media.cgov_file.field_media_file.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing.field_banner_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.cgov_hero_banner.field_desktop_hero.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.cgov_hero_banner.field_tablet_hero.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.media.cgov_contextual_image.field_media_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.media.cgov_image.field_media_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.media.cgov_image.field_override_img_featured.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.media.cgov_image.field_override_img_panoramic.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.media.cgov_image.field_override_img_social_media.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.media.cgov_image.field_override_img_thumbnail.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/field.field.media.cgov_infographic.field_infographic.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/cgov_migration.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.blogseries_en_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.blogseries_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.cgovimage_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.cgovimage_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.contextualimage_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.contextualimage_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.file_en_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.infographic_en_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.infographic_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.minilanding_en_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.minilanding_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_infographic_es_migration.yml

Ensure images are not migrated into one giant folder.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.embedded_feature_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.embedded_feature_card_no_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.panoramic_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.thumbnail_card_image.yml

(#2088) Application Page Promotional Templates

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/099_types.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/310_press_archive.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/article.content.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/nci-analytics-functions.js

* Removed "data-callout-link" attributes
* Removed "data-gov-delivery" attributes
* Replaced CalloutBoxClick() with CalloutBoxLinkTrack() and cleaned up selector logic
* CustomLink() & default value cleanup
* More yaml for testing

(#2055) update data attributes for analytics click functions

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/megamenu/megamenu.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/index.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/cards/media--cgov-infographic--multimedia-card.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/cards/paragraph--cgov-card-raw-html--default.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/cards/paragraph--cgov-card-raw-html--landing-guide-card.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/paragraph--cgov-column-two.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/paragraph--cgov-guide-row.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/layout/html.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/infographic/media--cgov-infographic--infographic-display-article-large.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/infographic/media--cgov-infographic--infographic-display-article-medium.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/gulpfile.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/package-lock.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/package.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/postcss.config.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_blogs.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/templates/embeds/infographic/media--cgov-infographic--infographic-display-article-large.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/templates/embeds/infographic/media--cgov-infographic--infographic-display-article-medium.html.twig

ODE: http://ncigovcdode193.prod.acquia-sites.com

(#1889, #1981, #2048, #2065, #2052, #2077, #2081, #2079, #1139, #2084, #2085) Bugfixes/brendan 46

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/blog_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/node--cgov-blog-series--full.html.twig

* Added logic to draw card or browser title for Blog Topic and Archive series pages

(#2092) Dynamic Page Title Should Pull Card Title

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/press_release/field--node--field-citation--cgov-press-release.html.twig
docroot/profiles/custom/cgov_site/translations/cgov_site.es.po

* Add Spanish Citation heading on Press Release to translation file
* Update Press Release Citation field file to use translation context
* Closes #2094

(#2094) Spanish Citation heading on Press Release

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/CmsProtectionSubscriber.php

* check for all login routes
closes #2080

(#2080) Check for all login routes

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.blogpost_es_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_biography_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_citation_migration.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/010_coping_feelings_stress_fs.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/013_press_release_no_date_placeholder.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/030_breast-reconstruction-after-mastectomy.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/031_article_side_effects_treatment.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/040_article_no_date_placeholder.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/206_blog_post_NCI_director_d.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/302_press_release_leukemia.content.yml
scripts/utility/cgov_migration_load.sh

Closes #2101 
* Updates the citation text format in migrations.
* Updates the migration shell script to add biography and event.
* Reorganizes the shell script to add DCEG to the main case.
* Updates field_citation_content to the streamlined textformat in YAML content.

(#2101)  Update field_citation_content text format in migrations and .yml

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/ResponseCacheSubscriber.php

This also applies to 500 errors and 302s.

(#1811) Reduce 404 Cache Max Age

---

docroot/profiles/custom/cgov_site/cgov_site.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/config/install/core.entity_view_mode.block_content.embedded_feature_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/config/install/core.entity_view_mode.block_content.embedded_feature_card_no_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/config/install/embed.button.insert_block_content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/cgov_external_link_block.features.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/cgov_external_link_block.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/cgov_external_link_block.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/cgov_external_link_block.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/block_content.type.cgov_external_link_block.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/core.entity_form_display.block_content.cgov_external_link_block.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/core.entity_view_display.block_content.cgov_external_link_block.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/core.entity_view_display.block_content.cgov_external_link_block.embedded_feature_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/core.entity_view_display.block_content.cgov_external_link_block.embedded_feature_card_no_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/field.field.block_content.cgov_external_link_block.field_featured_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/field.field.block_content.cgov_external_link_block.field_override_card_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/field.field.block_content.cgov_external_link_block.field_override_card_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/field.field.block_content.cgov_external_link_block.field_override_image_promotional.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/field.storage.block_content.field_featured_url.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/field.storage.block_content.field_override_card_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/field.storage.block_content.field_override_card_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/field.storage.block_content.field_override_image_promotional.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_external_link_block/config/install/language.content_settings.block_content.cgov_external_link_block.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/cards/block-content--cgov-external-link-block--embedded-feature-card-no-image.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/cards/block-content--cgov-external-link-block--embedded-feature-card.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/templates/embeds/cards/block-content--cgov-external-link-block--embedded-feature-card-no-image.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/templates/embeds/cards/block-content--cgov-external-link-block--embedded-feature-card.html.twig

- Created block_content bundle
- Implemented templates
- Reconfigured Embed Button for Block to
allow Feature Card templates.
Closes #2050

(#2050) External Link Block

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install

Includes update hook to add permissions to existing role
Closes #2129

(#2129) Missing Media Moderation Tab

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_file/src/EventSubscriber/DirectFileDownloadSubscriber.php

(#2139) PDFs Not Opening in Browser

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/cgov_biography.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/011_biography_campuses.content.yml

(2143) Remove bio taxonomy creation on site install, add YAML content.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/floatingDelighter/rules.js

ODE: http://ncigovcdode223.prod.acquia-sites.com

(#2133, #2165) Bugfixes

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.tokens.inc
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/core.entity_view_display.node.cgov_blog_series.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogTopicIntro.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogTopicTitle.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/DisqusComments.php
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/block--cgov-blog-topic-intro.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/block--cgov-blog-topic-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/node--cgov-blog-series--full.html.twig

[Closes #2109 ]
[Closes #2112 ]
[Closes #2116 ]
[Closes #2178 ]

(#2109, #2112, #2116, #2178) Blog bug fixes, July

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoPlayer/flexVideo.js

Ticket/2191  video autosuggest fix

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_print.scss

added embedded entity sizing rules that were previously hidden because of media query

(#2186) embedded entity sizing rules added to print stylesheet

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/AppMeasurement.custom.js

* Cleaned up setNciPageNameAdditions() and set pageName to omit concatenated local pn values
* Removed dynamic "D=" value from HomePageDelightClick()
* Moved cgvBlogPost name/group into Appmeasurement.custom

(#2201, #2202, #2203) WA PageName value issues (#290)

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/green/entrypoints/Green.scss

formatting green theme scss and styling feature-secondary elements

(#2209) Secondary feature card styling on homelanding pages

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/simple_sitemap.settings.yml
patches/drush/4136-request-uri-fix.patch

Fix Sitemap Issues

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/js/plugins/cgov_glossifier/dialogs/glossify.js

(#2264) Fix glossifier URL

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/views.view.cgov_events.yml

Closes #2245
ODE: http://ncigovcdode238.prod.acquia-sites.com

Fix sorting for upcoming and past events view.

---

cgov-drupal-users.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install

Add previewer (content_previewer) to set of users for local testing.

(#2256) Add 'view latest version' permission to content_previewer role.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_series.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/metatag.metatag_defaults.node__cgov_cancer_center.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/metatag.metatag_defaults.node__cgov_cancer_research.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/metatag.metatag_defaults.node__cgov_cthp.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_home_landing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_mini_landing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/metatag.metatag_defaults.node__cgov_press_release.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.node__cgov_video.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/metatag.metatag_defaults.node__pdq_drug_information_summary.yml

* Removes event53 from non-Blog-Post pages
* Closes #2277

(#2277) Metatag fixes

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/user.settings.yml

(#2293) Disable user notifications

---

acsf-convert/files/factory-hooks/post-settings-php/z_new_relic.php

(#2286) Configure ACSF for New Relic

---

acquia-pipelines.yml

(#2302) Update Pipelines configuration to use PHP 7.2

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml

(#2303) Fix PDQ Meta Titles - Again

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/filter.format.streamlined.yml

Closes #2246 
ODE: http://ncigovcdode245.prod.acquia-sites.com

(#2246) Add additional allowed anchor attributes to Streamlined format.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/cgov_cancer_research.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/cgov_cancer_research.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_form_display.node.cgov_cancer_research.default.yml

Closes #2307
Closes #2290 
ODE: ncigovcdode251.prod.acquia-sites.com

(#2307, #2177) Update Cancer Research List paragraphs, Translation Date Display

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc

* Update site section token to get node in correct language
* Fixes issue with Spanish Blog Posts getting English content group name
* Closes #2279

(#2279) Fix Spanish blog analytics

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/cgov_saml_auth_config.module

(#2320) Return 403 when SSO User not Found

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.info.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/page/page--404-en.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/page/page--404-es.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_errorPage.scss

Closes #2310 .
Created new region for use on 404 pages.  Error page content will now be a new manual task to create custom blocks.

(#2310)Create new region for 404 page content

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/mainNav/mobilemenu.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_nav.scss

Closes #2144 .
Closes #2295 .
ODE: http://ncigovcdode247.prod.acquia-sites.com/
Switched to vw units so that nav element gets more reliable width and updated viewport meta tag

Mobile menu toggle fix for certain browsers

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogFeaturedPosts.php

Closes #2114 
ODE: http://ncigovcdode248.prod.acquia-sites.com

(#2114) Default to card title for featured blog posts in the right rail.

---

blt/blt.yml
docroot/modules/custom/app_module/app_module.info.yml
docroot/modules/custom/app_module/app_module.links.action.yml
docroot/modules/custom/app_module/app_module.links.menu.yml
docroot/modules/custom/app_module/app_module.permissions.yml
docroot/modules/custom/app_module/app_module.routing.yml
docroot/modules/custom/app_module/config/schema/app_module.schema.yml
docroot/modules/custom/app_module/src/AppModuleInterface.php
docroot/modules/custom/app_module/src/Controller/AppModuleListBuilder.php
docroot/modules/custom/app_module/src/Entity/AppModule.php
docroot/modules/custom/app_module/src/Form/AppModuleDeleteForm.php
docroot/modules/custom/app_module/src/Form/AppModuleForm.php
docroot/modules/custom/app_module/tests/modules/app_module_test/app_module_test.info.yml
docroot/modules/custom/app_module/tests/modules/app_module_test/config/install/app_module.app.test_app_module.yml
docroot/modules/custom/app_module/tests/src/Functional/AppModuleEntityTest.php
docroot/profiles/custom/cgov_site/cgov_site.info.yml

- Created the skeleton app module
- Created Functional Tests
- Updated blt.yml to allow for tests in module
- Added the app_module to the profile's list of modules

(#2334) Create initial App Module Entity Type

---

docroot/modules/custom/app_module/config/schema/app_module.schema.yml
docroot/modules/custom/app_module/src/AppModules.php
docroot/modules/custom/app_module/src/Plugin/Field/FieldFormatter/AppModuleReferenceFieldFormatter.php
docroot/modules/custom/app_module/src/Plugin/Field/FieldType/AppModuleReferenceItem.php
docroot/modules/custom/app_module/src/Plugin/Field/FieldWidget/AppModuleReferenceSelectWidget.php
docroot/modules/custom/app_module/tests/src/Functional/AppModuleFieldBrowserTestBase.php
docroot/modules/custom/app_module/tests/src/Functional/AppModuleReferenceFieldFormatterTest.php
docroot/modules/custom/app_module/tests/src/Functional/AppModuleReferenceSelectWidgetTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_form_display.node.cgov_application_page.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.embedded_feature_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.embedded_feature_card_no_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.panoramic_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.thumbnail_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_application_module.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.storage.node.field_application_module.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/application_page/node--cgov-application-page--full.html.twig

- Includes initial formatter, widget and type
- and schema!
- Includes tests for initial version
- Added field to cgov_application_page

(#2339) Created App Module Reference Field

---

composer.json
composer.lock
docker/web/Dockerfile
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/system.image.yml

- Replace default image manipulation toolkit with ImageMagick.
- New update hook in cgov_image to install the drupal/imagemagick module.
- Add imagemagick as a cgov_image dependency.
- Add system.image configuration to cgov_site.
- Add ImageMagick to the web Docker service for local development.
Closes #2335 
ODE: http://ncigovcdode258.prod.acquia-sites.com/

(NCIOCPL#2335) The automatic resizing of images can run out of memory.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/AppMeasurement.custom.js

Line 171 is the important change. The other lines are from whitespace issues which the IDE automatically fixed to match our style.
Closes #2405

(#2405) Fix URS tracking issue

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogCategories.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManagerInterface.php

Closes #2185 
ODE: http://ncigovcdode249.prod.acquia-sites.com/

(#2185) Limit displayed blog categories to only those with blog posts in currrent language.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/AppMeasurement.custom.js

Fix click event analytics on CTHP and PDQ pages

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/layout/html.html.twig

Changed javascript loading order to have DTM page_bottom loaded last.

Analytics loading order issue

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogPager.php

Initialize variable with an empty list of posts in case there aren't any.
Closes #2426

(#2426) Cannot preview the first post in a blog series.

---

docroot/modules/custom/app_module/app_module.module
docroot/modules/custom/app_module/app_module.services.yml
docroot/modules/custom/app_module/src/AppModuleRenderArrayBuilder.php
docroot/modules/custom/app_module/src/AppModuleRenderArrayBuilderInterface.php
docroot/modules/custom/app_module/src/Plugin/Field/FieldFormatter/AppModuleReferenceFieldFormatter.php
docroot/modules/custom/app_module/src/Plugin/Field/FieldType/AppModuleReferenceItem.php
docroot/modules/custom/app_module/src/Plugin/app_module/AppModulePluginBase.php
docroot/modules/custom/app_module/src/Plugin/app_module/AppModulePluginInterface.php
docroot/modules/custom/app_module/src/Plugin/app_module/MultiRouteAppModuleBuilderBase.php
docroot/modules/custom/app_module/src/Plugin/app_module/MultiRouteAppModuleBuilderInterface.php
docroot/modules/custom/app_module/src/Plugin/app_module/MultiRouteAppModulePluginBase.php
docroot/modules/custom/app_module/templates/app-module.html.twig
docroot/modules/custom/app_module/tests/modules/app_module_test/app_module_test.services.yml
docroot/modules/custom/app_module/tests/modules/app_module_test/config/install/app_module.app.caching_app_module.yml
docroot/modules/custom/app_module/tests/modules/app_module_test/config/install/app_module.app.test_multi_route_app_module.yml
docroot/modules/custom/app_module/tests/modules/app_module_test/src/Plugin/app_module/CachingAppModulePlugin.php
docroot/modules/custom/app_module/tests/modules/app_module_test/src/Plugin/app_module/TestAppModulePlugin.php
docroot/modules/custom/app_module/tests/modules/app_module_test/src/Plugin/app_module/TestMultiRouteAppModulePlugin.php
docroot/modules/custom/app_module/tests/modules/app_module_test/src/TestMultiRoute/TestMultiRouteChickenBuilder.php
docroot/modules/custom/app_module/tests/modules/app_module_test/src/TestMultiRoute/TestMultiRouteDefaultBuilder.php
docroot/modules/custom/app_module/tests/src/Functional/AppModuleRenderArrayBuilderTest.php
docroot/modules/custom/app_module/tests/src/Kernel/AppModuleTemplateSuggestionsTest.php

- Created custom builder for generating app_module render arrays
- Create MultiRouteAppModule base for more easily creating
"controllers" for app module routes.
- Created theme_hook, suggestions, template preprocessor for app_module
- Implemented tests

(#2447) Implemented Much of the Rendering Logic

---

acsf-convert/files/docroot/sites/g/settings.php
acsf-convert/files/docroot/sites/g/sites.inc
acsf-convert/files/docroot/sites/sites.php
composer.lock

- Updates composer.lock to use v2.61 of drupal/acsf
- Updates acs-convert/files/docroot files:
- sites/sites.php
- sites/g/settings.php
- sites/g/sites.inc
Closes #2450

(NCIOCPL#2450) Update ACSF connector module to v2.61

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module

Enables the cgov_vocab_manager module.

Add an update hook to enable the cgov_vocab_manager.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module

* Increases the cgov_site_section update hook number and relocates the hook.
* Moves the existing cgov_article update hook from the .module to .install file.

Install the CGOV Vocab Manager.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module

(#2484) Fixes for cache tag invalidation when root and display options toggled.

---

docroot/modules/custom/app_module/src/AppPathStorage.php
docroot/modules/custom/app_module/src/AppPathStorageInterface.php
docroot/modules/custom/app_module/src/Plugin/Field/FieldFormatter/AppModuleReferenceFieldFormatter.php
docroot/modules/custom/app_module/src/Plugin/Field/FieldType/AppModuleReferenceItem.php
docroot/modules/custom/app_module/tests/src/Kernel/AppPathStorageTest.php
docroot/modules/custom/app_module/tests/src/Kernel/AppPathTest.php
docroot/modules/custom/app_module/tests/src/Unit/AppPathManagerGetPathTest.php
docroot/modules/custom/app_module/tests/src/Unit/AppPathManagerUpdatePathDataTest.php

- Changed it to a MapDataDefinition and the schema to auto serialize.
- Updated AppPathStorage to take in array for data instead of string. (This was actually incorrectly marked as string even though it was being serialized and deserialized.)
- Updated tests to reflect arrays
- Added tests to AppPathTest in order to make sure field_application_module nodes save and update correctly.
Closes #2495

(#2495) Implemented data property correctly.

---

docroot/modules/custom/app_module/src/Plugin/Field/FieldWidget/AppModuleReferenceSelectWidget.php
docroot/modules/custom/app_module/tests/src/Functional/AppModuleFieldBrowserTestBase.php
docroot/modules/custom/app_module/tests/src/Functional/AppModuleReferenceSelectWidgetTest.php

- Updated AppModuleReferenceSelectWidget to accept JSON as a text string.
- Validation the string is JSON
- Updated tests.
Closes #2487

(#2487) Added App Module Settings Editing

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/core.entity_form_display.node.cgov_cthp.default.yml

Closes #2525
**ODE**: http://ncigovcdode289.prod.acquia-sites.com

(#2525) Update CTHP Overview Cards paragraphs widget to asymmetric.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_form_display.node.cgov_application_page.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.embedded_feature_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.embedded_feature_card_no_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.panoramic_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.thumbnail_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_app_module_page_template.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.storage.node.field_app_module_page_template.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_cts.content.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/application_page/page--cgov-application-page--no-left-nav.html.twig

* Add field_app_module_page_template to set whether to display left nav
* Add template suggestions for app module based on above field value
* Add page template to hide left nav for app modules
* Update CTS YAML content to hide left nav

(#2515) Hide/show left nav on app modules

---

docker/web/Dockerfile

Installs build-essential package (OS).
Pre-requisite for PR #2520/Issue #2519.

(NCIOCPL#2521) Update npm to 6.12.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/app_module/cts/app-module--cgov-cts-app--cgov-cts-app-module-plugin--view-details.html.twig

* Add template for view page in CTS app module
* Add isRehydrating flag for use in CTS react app
* Closes #2544

(#2544) Add isRehydrating flag to CTS view page

---

FrontendGlobals.json

- Affects lower-tier only.
Closes #2546

(2546) Set front end config for CTS.

---

docroot/modules/custom/app_module/app_module.services.yml
docroot/modules/custom/app_module/src/EventSubscriber/AppModuleRouteNormalizerBlockRequestSubscriber.php
docroot/modules/custom/app_module/src/PathProcessor/PathProcessorAppModule.php

This has a hard time being tested since the current app module on this branch does not really do anything. Also there is an issue with functional tests and making sure the path processor works. So this has been tested the best it can be.

(#2554) Fixes Normalization on Cached App Module Routes.

---

FrontendGlobals.json

(#2556) Add ZIP lookup endpoint to global config.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/application_page/node--cgov-application-page--full.html.twig

* Remove page title from app module node template
* Closes #2565

(#2565) Remove page title from app module page

---

docroot/modules/custom/cgov_cts/src/MultiRouteBuilders/CTSViewDetailsBuilder.php
docroot/modules/custom/cgov_cts/src/Services/ClinicalTrialsApiProxy.php
docroot/modules/custom/cgov_cts/tests/src/Unit/CTSViewDetailsBuilderTest.php

* Raise 404 error page if invalid-syntax or not found trial ID is given
* Closes #2588

(#2588) Trial description error page

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/layout/html.html.twig

* Add X-UA-Compatible meta tag for IE issues
* Closes #2591

(#2591) Add meta tag for IE issues

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveChat/LiveChat.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/_popupPartial.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/settings/ctsEnglishSettings.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/settings/ctsSpanishSettings.js

(#2472) Redirect CT LiveChat to ClinicalTrials queue. CGOV-10614

---

composer.json
composer.lock

* Updates Drupal Core to the latest 8.7.x release.
* Closes #2605
ODE: [ncigovcdode313.prod.acquia-sites.com](http://ncigovcdode313.prod.acquia-sites.com/user/login)

(#2605)  Update Drupal Core to 8.7.11

---

composer.json
composer.lock

The Drupal Core update should have gone to the `develop` branch, not a release branch.

 (#2605) Update Drupal Core to 8.7.11

---

FrontendGlobals.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/sitewideSearch/sitewideSearch.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/autocomplete/autocomplete.js

(#2611) Update sitewide search autosuggest to use webapi server.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.module

(#2660) Move update hook to install file.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/purple/entrypoints/Purple.scss

(#2628) Purple theme infographic button

---

blt/blt.yml
docroot/sites/settings/cgov_caching.settings.php

(#2651) Set up www-int-ac to use Akamai.

---

composer.json
composer.lock

- Purge to 8.x-3.0-beta9
- Akamai to 8.x-3.0-alpha7
Closes #2735

(#2735) Update Purge and Akamai modules

---

composer.json
composer.lock

Applies a patch to the `purge` contributed module to correct the flawed database logic which caused incorrect primary key values to be returned for new rows in the purge queue's database table.

(#2731) Fix disappearing purge requests.

---

composer.json
composer.lock
docroot/lib/CgovPlatform/Tests/CgovSchemaExclusions.php
docroot/profiles/custom/cgov_site/config/install/adobe_dtm.settings.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php

- Had to update composer file to create new repository for the
package. This is because the module project does not expose
its dev branch.
See https://www.drupal.org/project/adobe_dtm/issues/3117876
- Includes updated default install config
- Removed InstallDtm function
- This was done to set the environment of a non-prod environment to
the DTM staging version. This is different with launch, so it
is a moot point.
- Excluded adobe_dtm.settings from the test schema checking due to bug.
See https://www.drupal.org/project/adobe_dtm/issues/3117875

(#2653) Updated Adobe DTM Module to Support Launch

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/index.js

Closes #2750 .
Exposes proactivelivechat class and helper functions on the global window object.
**ODE:** 
http://ncigovcdode337.prod.acquia-sites.com/

(#2750) exposing proactive live chat to window

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_errorPage.scss

ODE: http://ncigovcdode342.prod.acquia-sites.com/form/thank-you 
Closes #2678 
Testing Notes:
Please verify the following look the same as on production:
-  404 error pages look the same. ( Must currently be manually created on the ODE)
- '/form/thank-you' (http://ncigovcdode342.prod.acquia-sites.com/form/thank-you)

(#2678) Updated breakpoint to dynamic

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/page-not-found.content.yml

* Create page_not_found region in YAML content
* Closes #2599

(#2559) Fix error pages on ODEs

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/cgov_yaml_content.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/cgov_yaml_content.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/950_embed_test.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/src/Service/CgovYamlContentEventSubscriber.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/src/Service/YamlEntityEmbedProcessor.php
hooks/common/post-code-deploy/post-code-deploy.sh
hooks/common/post-code-update/post-code-update.sh

- It is slightly dirty. There was no direct way to add it to our
yaml_content event subscriber class. So I had to add a
entity_presave hook. I do check that it is in the CLI at
least so it does not fire off when in the UI.
- Added a test YAML to ensure it works.
Closes (#2762)

(#2762) Implement Entity Embed Support in Yaml

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/cgov_infographic.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_form_display.media.cgov_infographic.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.infographic_display_article_large.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.infographic_display_article_medium.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.multimedia_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.thumbnail_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/field.field.media.cgov_infographic.field_caption.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/field.field.media.cgov_infographic.field_infographic.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/field.storage.media.field_infographic_mobile.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/020_infographic_pediatric_match.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/951_embed_infographic_large_test.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/951_embed_infographic_medium_test.content.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/infographic/infographic_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_images.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/templates/embeds/image/image_macros.twig

- Adds field_caption to the infographic CT and updates templates
- Enables the alt text for field_infographic, and adds logic for mobile
- Adds YAML content for infographic embeds
Closes #2703 
Closes #2765

Add field_caption and alt text to infographics.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.infographic_display_article_large.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.infographic_display_article_medium.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/infographic/infographic_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/nci-analytics-functions.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_images.scss
docroot/profiles/custom/cgov_site/translations/cgov_site.es.po

Closes #2786 
Closes #2769 
Closes #2783
ODE: 
http://ncigovcdode346.prod.acquia-sites.com/test/embed-info-med
http://ncigovcdode346.prod.acquia-sites.com/test/embed-info-lrg

(#2786, #2769, #2783) Infographic tweaks and analytics

---

FrontendGlobals.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/pdq/PDQ.js

(#2758) Load drug info summary pronunciation from media server.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/popups/glossaryPopups.js

Close #2823 
http://ncigovcdode357.prod.acquia-sites.com/

(#2823) Handle glossary terms with no pronunciation key.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/specialReport/SpecialReport.scss

ODE: http://ncigovcdode363.prod.acquia-sites.com
Closes #2833

(#2833) AP Link font family

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/specialReport/SpecialReport.scss

ODE: http://ncigovcdode362.prod.acquia-sites.com
Closes #2811

(#2811)  Scale hero image without gutters

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/specialReport/SpecialReport.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_special-report-raw.scss

ODE :  http://ncigovcdode370.prod.acquia-sites.com
- Fixes gradient for displays <390px
- Updates gradient height to 450px for desktop
- Removes fixed width from AP button on tablet/desktop
Closes #2582

(#2582)  Special Report Bugfixes

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/ResponseCacheSubscriber.php
docroot/sites/settings/cgov_fast_404.settings.php

(#2648) Configure fast 404.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing.field_landing_contents.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_form_display.media.cgov_contextual_image.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_form_display.media.cgov_image.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.block_content.cgov_image_carousel.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.media.cgov_contextual_image.image_reference_field_form.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.media.cgov_image.image_reference_field_form.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_mode.node.borderless_card_image.yml

ODE: http://ncigovcdode375.prod.acquia-sites.com
Closes #2859

(#2859) Fix for config / features dependency issues

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/node--cgov-home-landing--full.html.twig

Closes #2865
ODE: http://ncigovcdode378.prod.acquia-sites.com/

(#2865) Fix for invalid markup within the landing page node template.

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/modules/custom/cgov_caching_cdn/config/install/akamai.settings.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/MainNav.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.links.menu.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.permissions.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.routing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Form/InvalidateMainNavCacheForm.php
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/mainNav/mobilemenu.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/package-lock.json

In addition to caching the Main Menu it was found that memcache was not enabled, which was the underlying cause of everything being slow. Now we should be back to normal slow AND faster because of the nav. (The nav will still be slow to generate for now)
Closes  #2869
Closes #2875

(#2869) Enable Caching of Main Menu

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/mainNav/mobilemenu.js

(#2889) Fix the main menu state highlighting

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/minilanding/Minilanding.scss

ODE: http://ncigovcdode383.prod.acquia-sites.com
Closes #2894

(#2894) Bugfix for two column flex rows on mini-landing.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/specialReport/SpecialReport.scss

ODE: ncigovcdode387.prod.acquia-sites.com
Closes #2864

(#2864) AP Mobile Breakpoint Width

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/exitDisclaimer/exitDisclaimer.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_alternating-lists.scss

ODE: http://ncigovcdode388.prod.acquia-sites.com
Closes #2855

(#2855) Bugfix for alternating image external links

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/node--cgov-home-landing--full.html.twig
docroot/profiles/custom/cgov_site/translations/cgov_site.es.po

ODE: http://ncigovcdode386.prod.acquia-sites.com/
Closes #2845

(#2845)  Add AP 'share this page' translation 

---

hooks/common/post-code-update/post-code-update.sh

(2970) Make it possible to preserve environment on code update.

---

composer.lock
docker/web/Dockerfile
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/core.entity_form_display.taxonomy_term.cgov_biography_campuses.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_form_display.taxonomy_term.cgov_cancer_center_regions.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_form_display.taxonomy_term.cgov_cancer_center_types.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_form_display.taxonomy_term.cgov_event_series.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_form_display.taxonomy_term.cgov_event_venues.default.yml

(#2968) Update drupal/core to v8.9.9.

---

FrontendGlobals.json

(#2913) Replace CTS Proxy with direct use of clinicaltrialsapi.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/glossaryService/glossary-api-client-v1.js

* Update syntax for passing query params to axois get request
* Update spelling error in error message :)

(#3007) Glossary Term Links on HP Summaries

---

composer.lock

(#3013) Update drupal/core to 8.9.13

---

FrontendGlobals.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/cts/cts.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/package-lock.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/package.json

(#3026) updating CTS package with EDDL implementation

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/cts/cts.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/package-lock.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/package.json

Closes #3041 
Removed service instantiation from cts config which was getting overwritten in application anyway.  Essentially replaced when we added ctsHost, protocol and port 
Updated cts search app to `v1.2.1`

(#304) fix for CTS config

---

composer.lock

(#3047) Update drupal.core to 8.9.14

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.paragraph.cgov_card_borderless.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.paragraph.cgov_card_borderless.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.cgov_card_borderless.field_button_display.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.cgov_card_borderless.field_button_text.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.cgov_card_borderless.field_card_theme.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.cgov_card_borderless.field_image_position.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_button_alt.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_button_display.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_button_text.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_card_theme.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_image_position.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/960_test_borderless_card.content.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/cards/card_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/cards/paragraph--cgov-card-borderless.html.twig
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_borderless-cards.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_colors.scss

- Update paragraph type for custom landing page.
- Added three fields to paragraph type Borderless Full Width Feature card.
- Associated styling and template changes.
- Update yaml file for borderless content test.
Closes #2963 
Replacement for #3031

(#2963) Implement borderless full width feature cards.

---

composer.lock

(#3606) Drupal/Core to 8.9.15

---

composer.lock

(#3070) Update drupal/core to 8.9.16.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.media.cgov_contextual_image.field_accessible_version.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.media.cgov_image.field_accessible_version.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/field.field.media.cgov_infographic.field_accessible_version.yml

Closes: #2839 
ODE: http://ncigovcdode425.prod.acquia-sites.com/
Changed the label and also updated the tooltip.

(#2839) change label and tooltip on accessible text version field

---

docroot/profiles/custom/cgov_site/translations/cgov_site.es.po

ODE: http://ncigovcdode425.prod.acquia-sites.com
Updated <field_name>  Crédito to  Fuente in spanish.

(#2725) Update Credit Display Translation in Spanish

---

docroot/modules/custom/cgov_cts/tests/src/Unit/ZipCodeLookupResourceTest.php

Work around stupid undocumented Acquia configuration change.
Closes #3094

(#3094) Mock cache for ZipCodeLookupResourceTest.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php

(#3039) Resolve undefined variables in blog templates.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/field.field.node.cgov_blog_series.field_feedburner_url.yml

ODE: http://ncigovcdode425.prod.acquia-sites.com
Closes: #3055 
Updated the label on blog series as requested.

(#3055) Update Feedburner URL Label on Blog Series

---

docroot/modules/custom/cgov_cts/tests/src/Unit/ZipCodeLookupResourceTest.php

(#3117) Don't care how many times assertValidTokens is called.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovPurgeConfigInstaller.php

Closes: #3088 
Fixed the issue - Throw Exception correctly in CgovPurgeConfigInstaller.php

(#3088) Throw Exception correctly in CgovPurgeConfigInstaller

---

composer.json
composer.lock

This resolves a major issue where the akamai purge responses were being stored in the Drupal state, and causing HUGE performance issues.
This affects all versions of the module alpha8 and before. An alpha9 version has not been released yet, so we need to point at the dev branch.
Closes #3085

(#3085) Update Akamai module to fix mem issues

---

composer.lock

(#3140) Update drupal/core to 8.9.19.

---

blt/ci.blt.yml
docroot/modules/custom/app_module/app_module.services.yml
docroot/modules/custom/app_module/src/AppPathManager.php
docroot/modules/custom/app_module/tests/src/Unit/AppPathManagerTestBase.php
docroot/modules/custom/app_module/tests/src/Unit/AppPathManagerUpdatePathDataTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/PathProcessor/UrlProcessor.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/CgovNavigationManager.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/cgov_migration.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/CgovImporterService.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/src/Form/RedirectImport.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Plugin/Validation/Constraint/UniqueCgovUrlConstraintValidator.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_syndication/cgov_syndication.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Manager/CgovVocabManager.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/cgov_yaml_content.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/src/Service/CgovYamlContentEventSubscriber.php
docroot/profiles/custom/cgov_site/src/Form/CgovAlterForm.php

This resolves all deprecation notices.
ODE: https://ncigovcdode428.prod.acquia-sites.com/
Closes #3116
Closes #3106 
Closes #3107 
Closes #3114
Closes #3111 
Closes #3108
Closes #3109
Closes #3110 
Closes #3112 
Closes #3113 
Closes #3115 
Closes #2918

Resolve all deprecated code warnings

---

composer.json
composer.lock

* (#3120) Upgrade admin_toolbar module to version 3.0.2
* (#3119) Upgrade acquia_connector module to version 3.0.3
* (#3125) Upgrade sophron module to version 1.1.0
* (#3123) Upgrade seckit module to version 2.0.0
* (#3126) Upgrade twig_field_value module to version 2.0.0
Closes #3119
Closes #3120
Closes #3122
Closes #3125
Closes #3126

Module updates for drupal 9

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_disease_dynamic_trial_listing_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_intervention_dynamic_trial_listing_page.content.yml

(#3101) Added YAML for DLPs

---

composer.json
composer.lock

There is an issue with a change in 3.2 regarding how they determine if a page is cacheable or not. This is causing issues.
Closes #3227

(#3227) Revert purge module to 3.0

---

composer.json
composer.lock

(#3247) Update drupal/core to v9.2.9

---

scripts/pipelines/setup_env

(#3251) Set npm version in pipeline build.

---

docker/web/Dockerfile
scripts/pipelines/setup_app

Use a local copy of PhantomJS

---

simplesamlphp/CgovIdpTools.php
simplesamlphp/config/authsources.php
simplesamlphp/metadata/saml20-idp-remote.php

(3162) Make IDP selection configurable.

---

blt/blt.yml
composer.json
composer.lock
docroot/modules/custom/app_module/src/AppPathStorage.php
docroot/modules/custom/app_module/src/Plugin/Field/FieldType/AppModuleReferenceItem.php
docroot/modules/custom/app_module/src/Plugin/Field/FieldWidget/AppModuleReferenceSelectWidget.php

- Updating Drupal core to 9.2.16 version.
Closes #3320

Update Drupal core to 9.2.16

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.routing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Controller/CgovNavTreeController.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/tests/src/Functional/CgovSiteSectionNavApiTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/925_nav_api_test.content.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/config/install/cgov_common.settings.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/config/schema/cgov_common.schema.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/theme-settings.php

- create routes and implement controller for site section nav
- Still working on 4xx status code and cache tags.
ODE: https://ncigovcdode454.prod.acquia-sites.com/
Closes #3243

(#3243) Expose site nav as json api

---

composer.json
composer.lock

Newer versions, created to resolve the password prompt.
Better, cleaner fix than in #3354
Fixes #3353

(#3353) Update dmore/behat-chrome-extension and dmore/chrome-mink-driver

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/000_mobile_menu.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/footer-block.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/page-not-found.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/site-banner.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/utility-bar.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/src/Service/CgovYamlContentEventSubscriber.php

ODE: https://ncigovcdode463.prod.acquia-sites.com/
Closes #3351

(#3351) Supply theme in Yaml blocks

---

blt/blt.yml

Turn off seckit on local build.

---

docroot/modules/custom/cgov_adobe/config/install/cgov_adobe.settings.yml

ODE: https://ncigovcdode485.prod.acquia-sites.com/
Closes #3455

(#3455) Point Adobe Launch Config to Cgov Property

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/000_ncids_trans_blocks.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/ncids-common.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/ncids-common.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/__tests__/usa-footer.dom.mock.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/__tests__/usa-footer.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/_usa-footer.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/usa-footer.ts

Closes #3216 
ODE, this branches off inner pages, so only inner pages have the new footer for now
https://ncigovcdode480.prod.acquia-sites.com/about-cancer/coping/feelings

(#3216) Implement ncids footer

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.services.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Routing/DisallowedRouteSubscriber.php
docroot/sites/settings/cgov_core.settings.php

- Created a service to redirect /user/reset to home page

(#3441) Disable password reset functionality in Drupal

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoCarousel/flex-video-api.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoPlayer/flexVideo.js

- Addd sandbox attribute to flex video api js file
Closes #3430

(#3430) Add sandbox attribute to iframes

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/031_article_side_effects_treatment.content.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/ProactiveLiveHelp.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/_popupPartial.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/settings/ctsEnglishSettings.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/settings/ctsSpanishSettings.js

My first DP pull request.  Probably not my last. :-) 
I've added/modified YAML content to allow testing of Spanish popup window.
Closes #3444

Modifying chat button on proactive LiveHelp popup

---

FrontendGlobals.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_adult_metastatic_tumor_manual_trial_listing_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_cam_manual_trial_listing_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_chicken_pox_manual_trial_listing_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_covid19_manual_trial_listing_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_cts.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_disease_dynamic_trial_listing_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_intervention_dynamic_trial_listing_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_kidney_cancer_manual_trial_listing_page.content.yml

- created MLP yaml
- updated DLP and CTS yaml
- updated FrontEndGlobals
Closes #3471

(#3471) Created/updated yaml

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/ncids-common.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/ncids-common.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-site-alert/__tests__/usa-site-alert.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-site-alert/_usa-site-alert.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-site-alert/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-site-alert/usa-site-alert.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/blog/page--cgov-blog-post.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/blog/page--cgov-blog-series.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/cthp/page--cgov-cthp.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/page--cgov-home-landing--special-report.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/page--cgov-home-landing.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/page--cgov-mini-landing.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/layout/page.html.twig

ODE: http://ncigovcdode496.prod.acquia-sites.com/
Closes #3404

(#3404) Implement NCIDS Site Alerts

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/000_ncids_trans_blocks.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/__tests__/usa-footer.dom.mock.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/__tests__/usa-footer.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/usa-footer.ts

Closes #3509 
ODE http://ncigovcdode498.prod.acquia-sites.com

(#3509) Implement footer back to top changes

---

acquia-pipelines.yml
scripts/pipelines/tests_front_end

(#3511) Run Front-end Tests in Pipelines

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/__tests__/usa-footer.test.ts

Closes #3475
No ODE, check pipelines for error

(#3475) Fix footer submit unit test

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/page/page--404-en.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/page/page--404-es.html.twig

ODE: http://ncigovcdode501.prod.acquia-sites.com/
Closes #3386 
Check Error Pages at: 
https://ncigovcdode501.prod.acquia-sites.com/ErrorPages/404/
https://ncigovcdode501.prod.acquia-sites.com/espanol/ErrorPages/404/

(#3386) Update Error Pages

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/utilities/dateUtility.js

(#3514) Fix holiday date check for proactive chat

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-page-options/__tests__/cgdp-page-options.test.ts

Closes #3256 
Note: No ODE. Console unit test error only.

(#3256) Fixed Page Options Unit Test Error

---

docker/docker-compose.yml

(#3574) Backwards compatibility for M1 Macs

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Controller/CgovNavTreeController.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/925_nav_api_test.content.yml

- This also adds in Spanish test cases.
Closes #3604

(#3604) NCIDS Support for Section Nav

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/NcidsHeader.php

- The logos were not being marked as permanent, nor being registered and thus were being deleted when the temporary file deleter ran.
ODE: https://ncigovcdode510.prod.acquia-sites.com
Closes #3624

(#3624) Fix Disappearing Logos

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/blog/page--cgov-blog-post.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/blog/page--cgov-blog-series.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/cthp/page--cgov-cthp.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/layout/page_options_macros.twig
docroot/profiles/custom/cgov_site/translations/cgov_site.es.po

ODE: https://ncigovcdode512.prod.acquia-sites.com/
Closes #3588 
Closes #3582 
Closes #3628

Page Options Fixes

---

.github/workflows/ci.yml

(#3619) Update workflow to ubuntu 20.04

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/PageOptionsManager.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Unit/Plugin/Services/PageOptionsManagerTest.php

(#3660) Update legacy page options to match DS

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/page--cgov-mini-landing.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/layout/page.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/layout/page_options_macros.twig
docroot/profiles/custom/cgov_site/translations/cgov_site.es.po

(#3664) Page Options Acessibility Fix

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/000_ncids_trans_blocks.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/__tests__/usa-footer.dom.mock.ts

(#3665) Remove h4 footer headers

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/ProactiveLiveHelp.js

(#3680) LiveHelp Popup X Removal

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/tooltips/referenceTooltip.js

ODE: https://ncigovcdode526.prod.acquia-sites.com/
Closes #3698

(#3698) Citation Hover Fix

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/biography-stephen-chanock.content.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_alternating-lists.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_profile-panel.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/pdq/pdq-legacy.scss

ODE: https://ncigovcdode526.prod.acquia-sites.com/
Closes #3687 
Closes #3677 
Closes #3703

Spacing fixes

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/app-module/app-module-legacy.scss

(#3683) Pager Focus Cutoff Fix App Module

---

FrontendGlobals.json

(#3711) Remove trailing slash from r4r endpoint config

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mega-menu.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/mega-menu-analytics-handlers.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/nci-header.ts

(#3581) Header Logo Analytics

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/exitDisclaimer/exitDisclaimer.js
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/ncids-common.ts

(#3706) Exit Disclaimer Fix

---

simplesamlphp/config/acquia_config.php

(#3428) Make SimpleSAMLphp cookies secure

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/accordion/_accordion.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_lists.scss

(#3709) Accordion Padding Fix

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/legacy/styles/_hero.scss

I ended up just reverting most of the hero changes. So there are some additional items that will show on desktop -> widescreen.
Closes #3753

(#3753) Fix NCIDS Hero for widescreen

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install

(#3755) Add update hook to enable clam AV.

---

composer.json
composer.lock

closes #3023 - Spanish Translation Workflow Issue for Multimedia (Video, Infographic & File)
ODE https://ncigovcdode545.prod.acquia-sites.com/

(#3023) Spanish translation workflow issue for Multimedia.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_form_display.node.cgov_application_page.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/cgov_biography.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/core.entity_form_display.node.cgov_biography.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/core.entity_form_display.taxonomy_term.cgov_biography_campuses.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/language.content_settings.node.cgov_biography.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/language.content_settings.taxonomy_term.cgov_biography_campuses.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/core.entity_form_display.node.cgov_blog_post.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/core.entity_form_display.node.cgov_blog_series.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/page_manager.page_variant.node_view-panels_variant-blog-post.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/cgov_cancer_center.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_form_display.node.cgov_cancer_center.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_form_display.taxonomy_term.cgov_cancer_center_regions.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_form_display.taxonomy_term.cgov_cancer_center_types.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/language.content_settings.node.cgov_cancer_center.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/language.content_settings.taxonomy_term.cgov_cancer_center_regions.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/language.content_settings.taxonomy_term.cgov_cancer_center_types.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_form_display.node.cgov_event.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_form_display.taxonomy_term.cgov_event_series.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_form_display.taxonomy_term.cgov_event_venues.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/language.content_settings.node.cgov_event.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/language.content_settings.taxonomy_term.cgov_event_series.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/language.content_settings.taxonomy_term.cgov_event_venues.yml

(#3836) Make language selector visible on multiple content types.

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.autocomplete.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mega-menu.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mobile-menu.test.ts

(#3870) Add matchMedia to header jest dom tests

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php

closes #3869 -- RSSfeed Enclosure URL breaks for microsites.
ode https://ncigovcdode539.prod.acquia-sites.com

(#3869) RSSfeed Enclosure URL breaks for microsites.

---

composer.json
composer.lock
docroot/.htaccess
docroot/sites/default/default.settings.php

drupal 9.5.9 upgrade.
ODE: http://ncigovcdode554.prod.acquia-sites.com
Closes #3833

(#3833) Drupal 9.5.9 upgrade.

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-home-landing/ncids-home-landing.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/__tests__/cgdp-feature-card.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/__tests__/nci-feature-card-row.bad.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/__tests__/nci-feature-card-row.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/cgdp-feature-cards.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/core/analytics/__tests__/landing-click-tracker.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/core/analytics/landing-page-contents-helper.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/ncids_card_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/paragraph--ncids-feature-card-external.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/paragraph--ncids-feature-card-internal.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-3-feature-card-row.html.twig

Closes #3786
https://ncigovcdode558.prod.acquia-sites.com/ncids-internal-feature-card-test
https://ncigovcdode558.prod.acquia-sites.com/ncids-external-feature-card-test

(#3786) Add feature card analytics

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/views.view.blog_rss.yml

- Needed to update admin_label to force features into thinking that it
needs to update the configuration state.
Closes #3890

(#3890) Fix Blogs RSS

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-home-landing/ncids-home-landing.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-guide-card-row.bad.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-guide-card-row.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-guide-card-row.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/cgdp-guide-card-row.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/ncids_card_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-2-guide-card-row.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-guide-card-img-desc.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-external--link-button-guide-card.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-internal--link-button-guide-card.html.twig

Closes #3788 
ODE https://ncigovcdode563.prod.acquia-sites.com/ncids-guide-card-test

(#3788) NCIDS Guide Card with Img and Desc Analytics

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-home-landing/ncids-home-landing.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-cta-strip/__tests__/nci-cta-strip.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-cta-strip/__tests__/nci-cta-strip.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-cta-strip/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-cta-strip/nci-cta-strip.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-call-to-action-strip.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-external--link-button-cta.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-link-button-internal--link-button-cta.html.twig

(#3789) Add cta analytics 

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-inline-video/__tests__/cgdp-inline-video.bad.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-inline-video/__tests__/cgdp-inline-video.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-inline-video/__tests__/cgdp-inline-video.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-inline-video/cgdp-inline-video-analytics.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-inline-video/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-inline-video.html.twig

(#3860) Wire up inline video analytics 

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids_raw_html_test_page.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-home-landing/ncids-home-landing.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-raw-html/__tests__/cgdp-landing-raw-html.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-raw-html/__tests__/cgdp-landing-raw-html.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-raw-html/cgdp-landing-raw-html.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-raw-html/index.ts

Closes #3902
https://ncigovcdode575.prod.acquia-sites.com/ncids-raw-html-test

(#3902) Wire up raw html block analytics

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-promo-block-external.html.twig

Closes #3895
ODE: https://ncigovcdode571.prod.acquia-sites.com/

(#3895) Empty p tag NCIDS External Promo Block

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_guide_card_img_desc.field_image_guide_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_hero.field_desktop_hero.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_hero.field_mobile_hero.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_hero.field_mobile_large_hero.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_hero.field_tablet_hero.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_hero.field_tablet_large_hero.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_hero.field_widescreen_hero.yml

(#3906) File Directories for NCIDS Hero and Guide Cards

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-cta-strip/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-2-guide-card-row.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-call-to-action-strip.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-guide-card-img-desc.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-hero.html.twig

Closes #3879
ODE: https://ncigovcdode579.prod.acquia-sites.com/

(#3879) Add aria-labelledby to components

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-guide-card-row.bad.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-guide-card-row.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-guide-card-row.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/cgdp-guide-card-row.ts

Closes #3918
ODE: https://ncigovcdode581.prod.acquia-sites.com/

(#3918) Guide Card Analytics Bug Fix

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_external.field_override_card_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_external.field_override_card_title.yml

Closes #3921
ODE: https://ncigovcdode582.prod.acquia-sites.com/

(#3921) External Feature Card Tooltip Text Fix

---

.github/workflows/ci.yml
.github/workflows/ocpl_cm_standards_check.yml

Github Workflow Updates

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/__tests__/cgdp-mobile-menu-adaptor.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/__tests__/data/section-nav/844114.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/cgdp-mobile-menu-adaptor.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/nci-header.ts

Closes #3674
ODE: https://ncigovcdode587.prod.acquia-sites.com/
Testing link from ticket: https://ncigovcdode587.prod.acquia-sites.com/publications

(#3674) Mobile Menu Fix

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.paragraph.ncids_hero.default.yml

ODE: https://ncigovcdode586.prod.acquia-sites.com/
Closes #3934

(#3934) Remove lazy loading from NCIDS Hero

---

blt/blt.yml
composer.json
composer.lock
docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/cgov_saml_auth_config.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/cgov_saml_auth_config.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/config/install/autologout.settings.yml
docroot/sites/settings/cgov_core.settings.php

Testing scenarios on tickets.
Closes #1700 
Closes #2061

(#1700) Enable automated logouts

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php

Closes #3907
ODE https://ncigovcdode598.prod.acquia-sites.com

(#3907) Resolved RSS feed image length issue

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_file/config/install/core.entity_view_display.media.cgov_file.ncids_feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_3_feature_card_row.field_row_cards.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_mode.media.ncids_feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.ncids_feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/cgov_promo.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_form_display.paragraph.ncids_feature_card_multimedia.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_view_display.paragraph.ncids_feature_card_multimedia.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_multimedia.field_featured_media.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_multimedia.field_override_card_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_multimedia.field_override_card_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_multimedia.field_override_image_promotional.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.storage.paragraph.field_featured_media.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/paragraphs.paragraphs_type.ncids_feature_card_multimedia.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/993_ncids_feature_card_multimedia_test_page.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/__tests__/cgdp-feature-card.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/media--ncids-feature-card-image.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/paragraph--ncids-feature-card-multimedia.html.twig

Closes #3637
ODE: https://ncigovcdode596.prod.acquia-sites.com/

(#3637) Build NCIDS Feature Card Multimedia

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.paragraph.ncids_3_guide_card_row.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.paragraph.ncids_guide_card.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.paragraph.ncids_3_guide_card_row.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.paragraph.ncids_guide_card.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_landing_contents.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_3_guide_card_row.field_container_heading.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_3_guide_card_row.field_guide_cards.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_guide_card.field_container_heading.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_guide_card.field_link_buttons.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/paragraphs.paragraphs_type.ncids_3_guide_card_row.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/paragraphs.paragraphs_type.ncids_guide_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/996_ncids_guide_card_test_page.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-3-guide-card-row.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-guide-card-row.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/cgdp-guide-card-row.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/field--paragraph--field-guide-cards--ncids-3-guide-card-row.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/field--paragraph--field-link-buttons--ncids-guide-card.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-3-guide-card-row.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-guide-card.html.twig

Closes #3942 
Closes #3943 
ODE: https://ncigovcdode594.prod.acquia-sites.com/

(#3942) Build NCIDS Guide Card

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module

Closes #3962
ODE: https://ncigovcdode600.prod.acquia-sites.com/

(#3962) Promo Block Production Error Fix

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_button_text.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/996_ncids_guide_card_test_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/997_ncids_cta_title_test_page.content.yml

(#3949) Update Link Button Text Char Limit

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_promo_block_external.field_ncids_theme.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_promo_block_internal.field_ncids_theme.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_ncids_theme.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/994_ncids_external_promo_block_test_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/995_ncids_internal_promo_block_test_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids_hero_button_test_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids_hero_cta_test_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids_hero_dark_button_test_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids_hero_dark_cta_test_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids_hero_dark_default_test_page.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids_grants_training.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids_homepage.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_sample_page_sample_1.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_sample_page_sample_2.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_sample_page_sample_4.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-hero/__tests__/nci-hero.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-hero/__tests__/nci-hero.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-hero/nci-hero.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-hero.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-promo-block-external.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-promo-block-internal.html.twig

Closes #3944
ODE: https://ncigovcdode604.prod.acquia-sites.com/

(#3944) NCIDS Dark Hero

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Field/FieldFormatter/CgovDateFormatter.php
phpcs.xml
phpstan.neon

Closes #3983
ODE -- https://ncigovcdode607.prod.acquia-sites.com/

(#3983) Removed unused code in cgovdateformatter

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Form/FrontendGlobalsForm.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/PageOptions.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/PageOptionsManager.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/FieldStorage/CGovFieldStorageTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/FieldStorage/CgovMediaFieldStorageTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/RolesTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/TestKernelTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Unit/Plugin/Block/PageOptionsTest.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/tests/src/Kernel/CgovImageFieldStorageTest.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/tests/src/Kernel/FieldStorage/PDQFieldStorageTest.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/tests/src/Kernel/WorkflowTest.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/tests/src/Functional/ApiTest.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/tests/src/Functional/ApiTest.php
docroot/profiles/custom/cgov_site/tests/src/Functional/PdqNodeTypeTest.php
patches/drupal/3322743-FieldConfig-loadByName-return-type-issue.patch
phpcs.xml
phpstan.neon

(#3994) phpstan quick fixes for profiles modules

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_ncids_theme.yml

- We cannot remove any list field options that exist in data. (field_ncids_theme)
- Fixes the issue with the schema change for field_button_text.
ODE: https://ncigovcdode614.prod.acquia-sites.com/
Closes #4005

(#4005) Fix Config Issues

---

docroot/sites/settings/cgov_core.settings.php

(#4019) Fixes production logout destination

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Plugin/Validation/Constraint/UniqueCgovUrlConstraintValidator.php
phpstan.neon

ODE: https://ncigovcdode622.prod.acquia-sites.com/
Test Notes:
- Validate site section in all content types  and media types. It should be unique and should throw error if it is already used.
Closes #4024

(#4024) PHPStan issues with UniqueCgovUrlConstraintValidator

---

.github/workflows/ci.yml
.github/workflows/test-deployability.yml

(#4006) Successful Updates

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.module
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/ApiTest.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/Commands/RevisionPrunerCommands.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/Plugin/rest/resource/PDQResource.php
docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/src/Plugin/CKEditorPlugin/CgovGlossifier.php
phpcs.xml
phpstan.neon

- removed suppression of checks for PDQ files
- resolved the problems identified by phpcs and phpstan
Closes #4028

(#4028) fix PDQ deprecation notices

---

composer.json
composer.lock

ODE -- https://ncigovcdode631.prod.acquia-sites.com/
Closes #4029

(#4029) Drupal upgrade 9.5.10

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/CmsProtectionSubscriber.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/TranslationAvailableSubscriber.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_file/src/EventSubscriber/DirectFileDownloadSubscriber.php
phpstan.neon

(#4026) PHPStan issues in some EventSubscribers

---

docroot/profiles/custom/cgov_site/tests/src/Functional/CgovSiteTest.php
phpstan.neon

(#4072) phpstan issue CgovSiteTest.php

---

composer.json
composer.lock

(#3542) update memcache

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php
phpstan.neon

https://www-test-ac.cancer.gov/
Closes #4068

(#4068) phpstan issue ICalendarController

---

composer.json
composer.lock
patches/acquia/memcache.settings-hack-for-4033.patch

(#4033) Do not enable memcache on ODEs

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/theme-settings.php
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.theme
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/theme-settings.php
phpstan.neon

ODE - https://ncigovcdode638.prod.acquia-sites.com/
Closes #3993

(#3993) phpstan issue cgov_common ncids_trans themes

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/src/Plugin/Mail/CgovMailLogger.php
phpstan.neon

(#4051) phpstan issue CgovMailLogger

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module

(#4073) drupal10 deprecation cgov_core.module

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/ResponseCacheSubscriber.php
phpstan.neon

ODE - https://ncigovcdode640.prod.acquia-sites.com/
Closes #4053

(#4053) phpstan issue ResponseCacheSubscriber

---

composer.json
composer.lock

(#3544) Update ctools to 4.0

---

composer.json
composer.lock

(#3844) Update viewsreference to v2.0-beta6

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_redirect_manager/tests/src/Functional/CgovImporterServiceTest.php

(#4144) Fixes redirect manager test random failures

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Controller/CgovNavTreeController.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/FixHomeUrlAliasOutboundPathProcessor.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Form/CgovVocabManagerForm.php

Closes #3974
ODE: http://ncigovcdode648.prod.acquia-sites.com/

(#3974) Site Section & Vocab Manager phpstan fixes

---

composer.json
composer.lock

Closes #4184
Closes #4186 
Full regression testing (including manual page editing).

(#4184, #4186) Apply patch for paragraphs_asymmetric_translation_widgets

---

.github/workflows/ci.yml
.github/workflows/test-deployability.yml
docker/web/Dockerfile

Closes #4171 
Closes #4176 
Closes #4182 
Standard regression tests only.
[ODE 658](http://ncigovcdode658.prod.acquia-sites.com/)

(#4171, #4176, #4182) Remove drush & blt launchers, remove drupal console.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_sample_page_sample_2.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_sample_page_sample_3.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_sample_page_sample_4.content.yml

(#4025) Update Sample Page YAML

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/metatag.metatag_defaults.node__cgov_application_page.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.global.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.node.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/metatag/Group/CgdpAdvanced.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/metatag/Tag/CgdpDomain.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/metatag/Tag/CgdpTemplate.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_home_landing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/metatag.metatag_defaults.media__cgov_infographic.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.media__cgov_video.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/svpc_liver-cancer-causes-risk-factors-and-prevention.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/svpc_liver-cancer-treatment.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/svpc_what-is-liver-cancer.content.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.tokens.inc
docroot/sites/settings/cgov_core.settings.php

Closes #3912
Closes #3990
ODE (both commits): https://ncigovcdode671.prod.acquia-sites.com/
Testing: Plan to test this PR on ACSF lower environment (multiple sites)

(#3912, #3990) Added new cgdp metatags

---

blt/src/Blt/Plugin/Commands/SlevenCommands.php
hooks/common/post-code-deploy/post-code-deploy.sh
hooks/common/post-code-update/post-code-update.sh

Closes #4208 
Closes #4209 
Closes #4210

(#4209, #4208, #4210) Refactor blt cgov:reinstall

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.paragraph.ncids_hero.default.yml

(#4231) Theme option missing for NCIDS Hero component

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module

ODE: https://ncigovcdode682.prod.acquia-sites.com/
Closes #3333

(#3333) Navigation Caches not Cleared when Landing Page is Archived

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_event/cgov_event.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Plugin/Validation/Constraint/EventStartEndTimeConstraint.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Plugin/Validation/Constraint/EventStartEndTimeConstraintValidator.php
docroot/translations/drupal-9.5.6.es.po

(#2922) Issue with event start and end times.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/CgovNavigationManager.php

(#4244) Behavior for the archival of Spanish landing page.

---

cgov-drupal-users.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
drush/Commands/cgov/CgovUserCommands.php

ODE: https://ncigovcdode691.prod.acquia-sites.com/
Closes #4240

(#4240) Remove language set preference for users

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/000_ncids_mega_menu.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/925_nav_api_test.content.yml

ODE: http://ncigovcdode706.prod.acquia-sites.com/
Closes #4249

(#4249) Incorrect paths in YAML content.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/601_factbook_pages.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-aids-funding.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-bypass-appropriations.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-html-amount.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-html-bar.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-html-nrsa.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-number-rpg-awards.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-rms-funding.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-rpg-cost-per-award.json

* Added config styling to charts to prevent label wrapping on y-axis
Closes #3830

(#3830) Highcharts have visual discrepancies when first loaded

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/601_factbook_pages.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-grants-contracts.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/Chart.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/chart.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/index.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/grants-contracts.js

* Fixed bug originally reported on #3329 (Added loading of data plugin and json file for geo location)
* Added data to Highcharts map object
* Updated json data file for FY 2022 and yaml content file
Closes #3446

(#3446) Update and Restore Grants & Contracts Chart

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_additional_library.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.node.cgov_home_landing.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.borderless_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.embedded_feature_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.embedded_feature_card_no_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.ncids_feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.ncids_promo_block_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.panoramic_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.teaser.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.thumbnail_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_additional_library.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_addl_library.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-lib-test/addl-lib-test.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-lib-test/addl-lib-test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/webpack.entries.js
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.libraries.yml

Closes #4236
ODE: https://ncigovcdode705.prod.acquia-sites.com/

(#4236) Add additional library to home and landing page

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_form_display.node.cgov_application_page.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.media.field_date_display_mode.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_date_display_mode.yml

ODE: https://ncigovcdode714.prod.acquia-sites.com/
Closes #4245

(#4245) Reorder reviewed and updated date checkboxes

---

drush/Commands/cgov/CgovUserCommands.php

(#4262) Enabling Admin user if its blocked.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/000_ncids_trans_blocks.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package-lock.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-home-landing/ncids-home-landing.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.autosuggest.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mega-menu-basepath.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mega-menu.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.without-search.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-autocomplete/__tests__/cgdp-autocomplete-adaptor.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-autocomplete/cgdp-autocomplete-adapter.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/__tests__/cgdp-megamenu-adapter.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/cgdp-megamenu-adapter.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/__tests__/cgdp-mobile-menu-adapter.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/cgdp-mobile-menu-adapter.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/nci-header.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/__tests__/usa-footer.dom.mock.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/usa-footer.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-sidenav/__tests__/usa-sidenav.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-sidenav/__tests__/usa-sidenav.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-site-alert/usa-site-alert.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-header.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-sidenav.html.twig

ODE: https://ncigovcdode720.prod.acquia-sites.com/
Closes #4268

(#4268) Update to newest version of NCIDS

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/099_types.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_cancer_types_landing_page.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/addl-cancer-types-landing-page.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/addl-cancer-types-landing-page.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-cancer-type-az-list/cgdp-cancer-type-az-list.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-cancer-type-az-list/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-find-a-cancer-type/cgdp-find-a-cancer-type.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-find-a-cancer-type/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-find-a-cancer-type/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/webpack.entries.js
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.libraries.yml

Closes #4223 
Closes #4268
Closes #4216
Closes #4217 
ODE: https://ncigovcdode708.prod.acquia-sites.com/

Redesign 2.4 - Cancer Types Landing Page

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc

(#2884) Spanish OG:Image is incorrectly pulling English image

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_cancer_types_landing_page.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package-lock.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/addl-cancer-types-landing-page.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-find-a-cancer-type/cgdp-find-a-cancer-type.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-find-a-cancer-type/index.scss

Closes #4315 
Closes #4314 
Closes #4312

Cancer Types Landing Page Bug Fixes

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_video/cgov_video.features.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/cgov_video.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/cgov_video.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_form_display.media.cgov_video.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.entity_browser_selected_entity.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.image_reference_field_form.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.link.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.multimedia_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.thumbnail_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_cthp_multimedia.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_large_no_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_large_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_medium_no_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_medium_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_ncids_inline.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_small_no_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_small_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_override_thumbnail_video.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.storage.media.field_override_thumbnail_video.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_cthp_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_large.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_medium.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_ncids_inline.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_small.yml

ODE: http://ncigovcdode730.prod.acquia-sites.com/
Closes #2260

(#2260) Add Override Thumbnail Image to Videos

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/metatag.metatag_defaults.node__cgov_application_page.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/metatag.metatag_defaults.node__cgov_article.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/metatag.metatag_defaults.node__cgov_biography.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_post.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_series.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/metatag.metatag_defaults.node__cgov_cancer_center.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/metatag.metatag_defaults.node__cgov_cancer_research.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.global.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/metatag.metatag_defaults.node__cgov_cthp.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_home_landing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_mini_landing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/metatag.metatag_defaults.media__cgov_infographic.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc
docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/metatag.metatag_defaults.node__cgov_press_release.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.media__cgov_video.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.node__cgov_video.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/metatag.metatag_defaults.node__pdq_drug_information_summary.yml

(#4247) Remove og:sitename metatag from drupal output

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package-lock.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package.json

(#4321) Bump NCIDS to 2.7.0

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_override_thumbnail_video.yml

(#4326) Fix for spanish override thumbnail video field.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_cthp_multimedia.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_large_no_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_large_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_medium_no_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_medium_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_ncids_inline.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_small_no_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_small_title.yml

ODE: https://ncigovcdode742.prod.acquia-sites.com/
Closes #4324

(#4324) Thumbnail video WYSIWYG issue

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/chart.scss

Closes #4288
* Added styling to remove bullet from Highcharts menu

(#4288) Extraneous bullets appear in Highcharts hamburger menu

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoPlayer/flexVideo.js

(#4075) Allow YouTube video pop ups.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Plugin/Validation/Constraint/ValidateParentConstraint.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Plugin/Validation/Constraint/ValidateParentConstraintValidator.php

ODE: https://ncigovcdode744.prod.acquia-sites.com/
Closes #3062

(#3062) same site section at root should not get created

---

docroot/sites/settings/cgov_core.settings.php
hooks/common/post-code-deploy/slack.sh
hooks/common/post-code-update/slack.sh

(#4276, #4277) ODE Config Updates & Slack Posts

---

tests/cypress/cypress.config.js
tests/cypress/cypress/e2e/tests/ContentCreationParallel/CancerResearch/index.js
tests/cypress/cypress/support/e2e.js
tests/cypress/package-lock.json
tests/cypress/package.json

(#4329) Added cypress network idle

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/601_factbook_pages.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-grants-contracts.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/Chart.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/grants-contracts.js

Closes #4283
* Added `exporting` config to base theme for all charts with adjustments for chart title
* Removed `exporting` config in `grants-contracts.js` and `grants-contracts.json` files
* Updated related yaml content files
* Updated exported chart background color

(#4283) Highchart PDF Export Issues

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package-lock.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-find-a-cancer-type/cgdp-find-a-cancer-type.ts

(#4303) Fix Combo Box no-results analytics

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/601_factbook_pages.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-html-amount.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-number-rpg-awards.json

Closes #4344
* Added `max`, `tickInterval`, and `tickAmount` for charts `html-amount`, and `number-rpg-awards`
* Updated yaml content for related files

(#4344) Highcharts: Inconsistency on Chart Y-axis max value

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/Chart.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/chart.scss
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/kawards-pie.js

Closes #3814
* Added styling for context menu button to reduce overlap on title

(#3814) Factbook High Chart Mobile Breakpoint Issues

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module

(#570) Prevent taxonomy term deletion.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.module

(#4341) Prevent Blog series deletion when blog posts are there.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.tokens.inc

(#4339) Adding empty condition check for the node blog series.

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-cancer-type-az-list/cgdp-cancer-type-az-list.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-cancer-types-landing-page/components/cgdp-find-a-cancer-type/cgdp-find-a-cancer-type.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-dynamic-list/__tests__/cgdp-dynamic-list.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/__tests__/cgdp-feature-card.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-guide-card-row/__tests__/cgdp-guide-card-row.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-inline-video/__tests__/cgdp-inline-video.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-raw-html/__tests__/cgdp-landing-raw-html.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-raw-html/cgdp-landing-raw-html.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-cta-strip/__tests__/nci-cta-strip.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-hero/__tests__/nci-hero.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-promo-block/__tests__/nci-promo-block.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/core/analytics/__tests__/landing-click-tracker.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/core/analytics/landing-page-contents-helper.ts

MLP can be tested at https://ncigovcdode784.prod.acquia-sites.com/test/raw-html-sample-page. Home/landing live at the normal locations.
ODE: https://ncigovcdode784.prod.acquia-sites.com/
Closes #4386

(#4386) Update landing page analytics to not be only for LP

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.install

(#4380) Sets default value for field_mlp_page_style on MLP

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_slim_hero.field_slim_hero_image.yml

Closes #4404
ODE: https://ncigovcdode797.prod.acquia-sites.com/

(#4404) Makes Slim Hero Image field required

---

composer.json
composer.lock

(#4374) Patch favicon module to fix CORS error on manifest file.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/accordion/accordion.js
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/ncids-common-legacy.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/legacy/styles/_general.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/article/field--field-article-body.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/pdq/field--otp-toc.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/press_release/field--node--field-citation--cgov-press-release.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/field/citation/field--field-citation.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/field/related_resources/field--field-related-resources.html.twig

Closes #4409
- Removed Generate Sub/Sup style from _general.scss

(#4409) Fix Header Skips for Article Things

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_general.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/blog/node--cgov-blog-post--lb-primary-content.html.twig

(#4411) Fix Header Skips for Blog

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_general.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/legacy/styles/_blogs.scss

(#4431) Recommended Content Header Fix

---

blt/blt.yml
blt/deploy-exclude-additions.txt
scripts/blt/deploy/.gitignore

(#4437) Exclude additional files from built artifact

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/config/install/sitebranding.settings.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.global.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/schema/cgov_core.schema.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Form/SiteBrandingSettingsForm.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc

(#4335) Allow site name in schema.org to be optional.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/editor.editor.ncids_streamlined_no_headings.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/filter.format.ncids_streamlined_no_headings.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.paragraph.ncids_summary_box.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.paragraph.ncids_summary_box.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing.field_landing_contents.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_summary_box.field_container_heading_wysiwyg.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_summary_box.field_html_content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.storage.paragraph.field_container_heading_wysiwyg.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/paragraphs.paragraphs_type.ncids_summary_box.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids-mini-landing-example-page-ras.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids-mini-landing-example-page.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-mini-landing/ncids-mini-landing.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-mini-landing/ncids-mini-landing.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/__tests__/cgdp-summary-box.dom.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/__tests__/cgdp-summary-box.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/cgdp-summary-box.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/index.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/field--paragraph--field-container-heading-wysiwyg--ncids-summary-box.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/field--paragraph--field-html-content--ncids-summary-box.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/paragraph--ncids-summary-box.html.twig

Closes #4450
Closes #4379
ODE: https://ncigovcdode820.prod.acquia-sites.com/

(#4379) NCIDS Summary Box - MLP

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/index.scss

- Closes #4434
_Add description_
Closes #<TICKET-NUMBER>
Items that the author of the PR is responsible for checking before submitted the PR.
Items the product team is responsible for reviewing.
 
Items the design team is responsible for reviewing.  
Items the development team is responsible for reviewing.

Updates font size of feature card title and description

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/event/event-legacy.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/mini-landing/mini-landing-legacy.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/legacy/styles/_events.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/event/node--cgov-event--event-list-item.html.twig

(#4412) Header Skips Event Listing Fix

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_file/src/EventSubscriber/DirectFileDownloadSubscriber.php

(#4446) Only PDFs open in the browser window.

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-flag-card-group/index.scss

(#4457) Flag Card Breakpoint Update

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_page_subheading.yml

(#4408) Subheading field on HL page is now translatable

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_test_embedded_videos.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/ncids-common-legacy.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/legacy/styles/_image-video-carousel.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/legacy/styles/_videos.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block_content/image_carousel/block-content--cgov-image-carousel--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block_content/video_carousel/block-content--cgov-video-carousel--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/media--cgov-video--multimedia-card.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--video-display-cthp-multimedia.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--video-display-large-no-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--video-display-large-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--video-display-medium-no-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--video-display-medium-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--video-display-small-no-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--video-display-small-title.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/video_macros.twig

(#4419) Fix Embedded Media A11Y

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Plugin/Validation/Constraint/UniqueCgovUrlConstraint.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Plugin/Validation/Constraint/UniqueCgovUrlConstraintValidator.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/src/Plugin/Validation/Constraint/ValidateParentConstraintValidator.php

(#3170) sitesection must have unique url.

---

composer.json
composer.lock
patches/drupal/core/wokraround-patch-for-3207813.patch

This addresses an intermittent issue with configurations being "lost" despite no code changes or deployments taking place.
See https://www.drupal.org/project/drupal/issues/3207813#comment-15778426.
Closes #4475

(#4475) Patch for intermittent configuration "disappearances".

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-image/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-video/index.scss

(#4486) Adds right padding to caption

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-wide-guide-card/index.scss

(#4485) Wide Guide Card Line Height Fix

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/NcidsHeader.php
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-header.html.twig

- Removes aria-label from anchor parent of logo
Closes #4500

(#4500) Updates header logo to have alt text

---

FrontendGlobals.json

(#4511) Add listing page endpoint to CTS config for local dev and ODEs.

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoCarousel/flex-video-api.js

(#4492) Added sandbox attributes to allow youtube video newtabs.

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/modules/custom/cgov_caching_cdn/cgov_caching_cdn.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovPurgeConfigInstaller.php
docroot/sites/settings/cgov_caching.settings.php
docroot/sites/settings/cgov_core.settings.php
docroot/sites/settings/cgov_saml_auth_config.settings.php
docroot/sites/settings/cgov_settings_utilities.inc
patches/drupal/purge/3460094-2.diff
patches/drupal/purge/3460094.diff

A couple of tickets that require messing with the settings files:
* Enables cache clearing by URL in Akamai
* Purges redirect URLs at redirect creation
Closes #1866
Closes #2745

(#1866, #2745) Akamai cache clearing per URL and redirect purges

---

docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/package-lock.json
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/package.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package-lock.json
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package.json

(#4543) Update Sass

---

composer.json
composer.lock

Until https://www.drupal.org/project/js_cookie/issues/3390616 is complete.
Closes #4505

(#4505) Add js-cookie as library

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.storage.node.field_app_module_page_template.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/986_ncids_application_page.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-application-page-left-nav/ncids-application-page-left-nav.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-application-page-left-nav/ncids-application-page-left-nav.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-application-page-no-left-nav/ncids-application-page-no-left-nav.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-application-page-no-left-nav/ncids-application-page-no-left-nav.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/webpack.entries.js
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.libraries.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/node--cgov-application-page--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/page--cgov-application-page--left-nav.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/page--cgov-application-page--ncids-left-nav.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/page--cgov-application-page--ncids-no-left-nav.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/application_page/page--cgov-application-page--no-left-nav.html.twig

(#4517) Create NCIDS templates for Application Pages

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-mini-landing/ncids-mini-landing.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.theme
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/node--cgov-mini-landing--ncids-default--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/mini_landing/page--cgov-mini-landing--ncids-default.html.twig

(#4534) Remove duplicate mains in MLP template

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/views/container.html.twig

(#4503) Remove views-element-container from News & Events

---

composer.json
composer.lock
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php

(#4518) Returning 404 error if event ID does not exist.

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/blogs/blogs-legacy.scss

(#2306) Center Alignment for Images in Blogs

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/metatag.metatag_defaults.node__cgov_application_page.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/metatag.metatag_defaults.node__cgov_article.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/metatag.metatag_defaults.node__cgov_biography.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_post.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_series.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/metatag.metatag_defaults.node__cgov_cancer_center.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/metatag.metatag_defaults.node__cgov_cancer_research.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.node.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/metatag.metatag_defaults.node__cgov_cthp.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_home_landing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_mini_landing.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/metatag.metatag_defaults.node__cgov_press_release.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.node__cgov_video.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/metatag.metatag_defaults.node__pdq_drug_information_summary.yml

**@NCIOCPL/qa-team** Please let @welshja know when this is on an ODE.
Closes #2288

(#2288) Updated metadata dcterms issue to capture only date

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/core.entity_form_display.taxonomy_term.cgov_biography_campuses.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/core.entity_form_display.taxonomy_term.cgov_blog_topics.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_form_display.taxonomy_term.cgov_cancer_center_regions.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/core.entity_form_display.taxonomy_term.cgov_cancer_center_types.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_form_display.taxonomy_term.cgov_event_series.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_form_display.taxonomy_term.cgov_event_venues.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/config/install/core.entity_form_display.taxonomy_term.cgov_site_sections.default.yml

(#3884) Updated taxonomy term language options.

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_ncids_inline.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids_homepage.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-inline-video/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--video-display-ncids-inline.html.twig

(#4488) Audio Described Home and Landing

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.paragraph.field_external_link_display.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/cgov_promo.info.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_form_display.paragraph.ncids_feature_card_external.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_view_display.paragraph.ncids_feature_card_external.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_view_display.paragraph.ncids_feature_card_external.ncids_flag_group_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_view_display.paragraph.ncids_feature_card_external.ncids_group_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_external.field_external_link_display.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_imageless_card_external.field_override_card_description.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_imageless_card_external.field_override_card_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/992_ncids_external_feature_card_test_page.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/ncids_card_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/paragraph--ncids-feature-card-external--default.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/paragraph--ncids-feature-card-external--ncids-group-card.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/paragraph--ncids-feature-card-internal--default.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/field--paragraph--field-row-cards--ncids-3-feature-card-row.html.twig

(#4493) External Link Overrides - NCIDS Feature Cards

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.paragraph.ncids_promo_block_external.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.paragraph.ncids_promo_block_external.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_promo_block_external.field_external_link_display.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/994_ncids_external_promo_block_test_page.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/ncids_home_landing_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/home_landing/paragraph--ncids-promo-block-external.html.twig

(#4495) External Link Options for Promo Block

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_form_display.paragraph.ncids_imageless_card_external.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_view_display.paragraph.ncids_imageless_card_external.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_view_display.paragraph.ncids_imageless_card_external.ncids_group_imageless_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_imageless_card_external.field_external_link_display.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids_mini_landing_imageless_cards.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/ncids_card_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/paragraph--ncids-imageless-card-external--ncids-group-imageless-card.html.twig

(#4497) Imageless Card Ext Link Options

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_form_display.paragraph.cgov_external_link.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_view_display.paragraph.cgov_external_link.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_view_display.paragraph.cgov_external_link.list_item_title.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_view_display.paragraph.cgov_external_link.list_item_title_desc.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_view_display.paragraph.cgov_external_link.list_item_title_desc_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_view_display.paragraph.cgov_external_link.list_item_title_desc_image_alternating.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_view_display.paragraph.cgov_external_link.ncids_list_item_title_desc.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_view_display.paragraph.cgov_external_link.ncids_list_item_title_desc_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.cgov_external_link.field_external_link_display.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/998_ncids-mini-landing-list-examples.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/listing/list_item_macros.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/listing/paragraph--cgov-external-link--ncids-list-item-title-desc-image.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/listing/paragraph--cgov-external-link--ncids-list-item-title-desc.html.twig

(#4647) External Link Options List

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/js/ckeditor5_plugins/glossifier/src/glossifyactioncommand.js
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ckeditor/ckeditor-ck-scope.scss

(#4668) Make glossify cancel button work

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.cgov_external_link.field_external_link_display.yml

(#4666) External Link Tooltip Update

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/cgov_press_release.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/400_breast_cancer_research.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/983_inner_page_title_tests.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/press-release/press-release.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-document-dates/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/article/node--cgov-article--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/cancer_research/node--cgov-cancer-research--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/event/node--cgov-event--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/content/press_release/node--cgov-press-release--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/infographic/media--cgov-infographic--full.html.twig
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/media/video/media--cgov-video--full.html.twig

(#4565) Convert Inner Page Titles to NCIDS Headings

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/article/article.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/biography/biography.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/cancer-center/cancer-center.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/cancer-research/cancer-research.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/event/event.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/infographic/infographic.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/press-release/press-release.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/video/video.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-article-footer-citation/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-article-footer/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-document-dates/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-public-use/index.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-related-resources/index.scss

- Tweaks article footer spacing 
Closes #4705

(#4705) Updates article footer to control spacing between its children

---

docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/js/ckeditor5_plugins/glossifier/src/glossifyactioncommand.js
docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/js/ckeditor5_plugins/glossifier/src/utils/content-preparation.js
docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/js/ckeditor5_plugins/glossifier/src/utils/suggestion-display.js

(#4685) Glossification breaking with italics

---

composer.json
composer.lock
patches/drupal/paragraphs/paragraphs-focus-on-last-added-paragraph-2569361-36-revised.patch

(#4675) CKeditor 5 jumping to top

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-dynamic-list/__tests__/cgdp-dynamic-list.test.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-dynamic-list/cgdp-dynamic-list.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/core/analytics/landing-page-contents-helper.ts

(#4657) Analytics changes to NCIDS Dynamic List

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/views.view.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/views.view.media.yml

(#4743) Duplicate items media list

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/blogs/blogs-legacy.scss

- Updates lists on blog posts to fix issue where the bullets / list styles were being removed
Closes #4733

(#4733) Updates Blog Post Lists

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/metatag/Tag/CgdpEventGroup.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/metatag/Tag/CgdpEventSeries.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/cgov_event.install
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_form_display.node.cgov_event.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.borderless_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.default.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.embedded_feature_card.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.embedded_feature_card_no_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.event_list_item.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.event_ncids_collection_condensed.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.full.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.ncids_feature_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.ncids_flag_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.ncids_list_item_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.ncids_promo_block_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.teaser.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.thumbnail_card_image.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_event_group.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.storage.node.field_event_group.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/language.content_settings.taxonomy_term.cgov_event_group.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/taxonomy.vocabulary.cgov_event_group.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/views.view.cgov_events.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/250_events_views.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/500_event_test.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids-mini-landing-dynamic-list-events.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/event-i-score-workshop.content.yml

(#4757) Update Events Dynamic List for MLPS Structure

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install

(#4773) Change text format for Intro Text on Article Pages

---

docroot/modules/custom/nci_definition/src/Plugin/CKEditor5Plugin/Glossifier.php
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/editor.editor.ncids_streamlined.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/editor.editor.ncids_streamlined_no_headings.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/filter.format.ncids_streamlined.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/filter.format.ncids_streamlined_no_headings.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/860_test_definition_links.content.yml
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js
docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/popups/glossaryPopups.js
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/article/article.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ckeditor/ckeditor-ck-scope.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/legacy/styles/_mainContent.scss

Test URLs:
* Article: https://ncigovcdode967.prod.acquia-sites.com/test/ncids-article-def-link-test
* MLP: https://ncigovcdode967.prod.acquia-sites.com/test/ncids-mlp-def-link-test
Closes #4720

(#4720) Add Glossification to NCIDS Streamlined

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/860_test_definition_links.content.yml
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/article/article.scss
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-on-this-page/index.scss

(#4806) Remove extra spacing OTP

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_landing_contents.yml

(#4308) Remove legacy allowed contents from home landing

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-aids-funding.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-bypass-appropriations.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-grants-contracts.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-html-amount.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-html-bar.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-html-extramural.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-html-nrsa.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-kawards-pie.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-management-fund.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-moonshot-obligations.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-number-rpg-awards.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-obligations-mechanism.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-program-structure.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-rms-funding.json
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-rpg-funding.json

(#4663) Factbook 2024 Update

---

docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/952_embed_infographic_test_pages.content.yml
docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/983_inner_page_article_footer.content.yml

(#4879) Update Event Yaml with different dates and time

---

docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-landing-content-block/cgdp-landing-content-block.ts
docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-summary-box/cgdp-summary-box.ts

Closes #4949
For testing: [ODE 1012](https://ncigovcdode1012.prod.acquia-sites.com/)

(#4949) Update Analytics for Glossified

---

.github/workflows/test-deployability.yml
blt/blt.yml

(#4966, #4967) Fix error on CI environments from purge queue emptying
